#!/usr/bin/python

import numpy
import MySQLdb as sql

print "Content-type: text/html\n\n"
print "<html><head><title>title</title></head>"
print "<body>"

database = "DMTPC_WIPP"
hostname = "rubin.lns.mit.edu"
username = "dmatter"
password = "seedark"

db = sql.connect(hostname, username, password, database)

query = "SHOW tables;"

cursor = db.cursor()
cursor.execute(query)
result = cursor.fetchall()

tables = []

for record in result:
    tables.append(record[0])

sep = "  "
print "<h1>Structure of Database for 4Shooter</h1>"
print "db = " +database+"<br>\n"
print "SHOW tables<br>\n"
print "DESCRIBE [tablename]<br>\n"
print "<br>\n"

tablestr = ""
maxentries=1
for table in tables:
    tablestr += sep+"<tr>\n"+sep+sep+"<td><b>"+table+"</b></td>\n"
    query = "DESCRIBE "+table
    #print query+"<BR>"
    cursor.execute(query)
    result=cursor.fetchall()
    if len(result) > maxentries:  maxentries = len(result)
    for record in result:
        tablestr += sep+sep+"<td>"+record[0]+"</td>\n"
    tablestr += sep+"</tr"
tablestr += "</table>"

print "<table border=1>\n"
print sep+"<tr><td><b>Table</b> <td colspan="+str(maxentries)+"><b>Table entries</b></td></tr>\n"
print tablestr
print "</body>"
print "</html>"

#
#print "in python!<br>"
###command='root -l -q -b test.C'
###os.system(command)
#print "out of python!<br>"
#

