#! /usr/bin/perl

use DM; 
use CGI ':standard'; 
use CGI::Carp qw(fatalsToBrowser); 
use Socket; 

print "Content-type:text/html\n\n";

$packed_ip = gethostbyname($DM::HOST); 
print $ENV{'REMOTE_ADDR'}."\n";
if ($ENV{'REMOTE_ADDR'} ne inet_ntoa($packed_ip))
{
  die "This page is only accessible on the slow control machine";
}

$db = DM->connect() or die ("Could not connect!\n"); 

my $newval = 1 - int(DM->check_hold()); 

$sql = "update busy set slow_hold = $newval"; 
$statement = $db->prepare($sql) or die "can't prepare query '$sql': $DBI::errstr\n"; 
$statement->execute() or die "can't execute query '$sql': $DBI::errstr\n"; 

