#!/bin/bash

#takes a list of five-digit run number and runs cleanData and quickRecon 
#on all of them.
#Usage: ./runbasiclist aaaaa bbbbb ccccc [...] nnnnn

export skimdir='./skim/'
export sortdir='./sort/'
export sumdir='./skim/sum/'

until [ -z $1 ]
do
    echo dmtpc_run$1.root > files$1.txt
    echo ./ > keys$1.txt
    
    ./bin/cleanSkim files$1.txt keys$1.txt $skimdir >> run$1.log 2>&1 &
    wait
    ./bin/createSummary dmtpc_run$1 $skimdir $sumdir >> run$1.log 2>&1 &

#    rm -f files$1.txt
#    rm -f keys$1.txt
    echo "Processing on run $1 Done"
    shift
done
