#!/bin/bash

echo dmtpc_run$1.root > files$1.txt
echo ./ > keys$1.txt

export skimdir='./skim/'

root -l -b -q "cleanSkim.C+(\"files$1.txt\",\"keys$1.txt\",\"$skimdir\")" >> run$1.log 2>&1 &
wait

rm -f files$1.txt
rm -f keys$1.txt
echo "Processing on run $1 Done"