#define WR5_TRAIN_NEW    \
/*worms.push_back("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_05102skim.root");*/\
/*worms.push_back("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_05100skim.root");*/\
/*worms.push_back("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_05048skim.root");*/\
worms.push_back("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04991skim.root");\
worms.push_back("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04989skim.root");\
worms.push_back("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04917skim.root");\
worms.push_back("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04854skim.root");\
worms.push_back("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04852skim.root");\
/*worms.push_back("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04791skim.root");*/\
worms.push_back("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04789skim.root");\
worms.push_back("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04742skim.root");\
worms.push_back("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04740skim.root");\
worms.push_back("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04738skim.root");\
worms.push_back("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04736skim.root");\
worms.push_back("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04734skim.root");\
worms.push_back("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04732skim.root");\
worms.push_back("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04730skim.root");\
/*worms.push_back("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04728skim.root");*/\
worms.push_back("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04726skim.root");\
worms.push_back("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04724skim.root");\
worms.push_back("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04722skim.root");\
worms.push_back("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04720skim.root");\
/*worms.push_back("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04718skim.root");*/\
worms.push_back("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04716skim.root");\
worms.push_back("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04714skim.root");\
worms.push_back("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04712skim.root");\
worms.push_back("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04710skim.root");\
worms.push_back("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04708skim.root");\
/*worms.push_back("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04706skim.root");*/\
worms.push_back("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04704skim.root");\
worms.push_back("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04702skim.root");\
worms.push_back("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04700skim.root");\
/*worms.push_back("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04698skim.root");*/\
worms.push_back("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04696skim.root");\
/*worms.push_back("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04694skim.root");*/\
worms.push_back("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04692skim.root");\
worms.push_back("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04604skim.root");\
worms.push_back("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04602skim.root");\
worms.push_back("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04556skim.root");\
worms.push_back("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04522skim.root");\
worms.push_back("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04520skim.root");\
worms.push_back("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04474skim.root");\
/*worms.push_back("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04472skim.root");*/\
worms.push_back("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04470skim.root");\
worms.push_back("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04468skim.root");\
worms.push_back("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04425skim.root");\
/*worms.push_back("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04423skim.root");*/\
worms.push_back("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04376skim.root");\
/*worms.push_back("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04334skim.root")*/;


#define WR5_TEST_NEW \
/*worms_test.Add("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04332skim.root");*/\
/*worms_test.Add("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_05101skim.root");*/\
/*worms_test.Add("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_05049skim.root");*/\
/*worms_test.Add("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_05047skim.root");*/\
worms_test.Add("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04990skim.root");\
worms_test.Add("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04918skim.root");\
/*worms_test.Add("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04916skim.root");*/\
worms_test.Add("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04853skim.root");\
worms_test.Add("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04851skim.root");\
worms_test.Add("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04790skim.root");\
/*worms_test.Add("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04788skim.root");*/\
worms_test.Add("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04741skim.root");\
worms_test.Add("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04739skim.root");\
worms_test.Add("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04737skim.root");\
/*worms_test.Add("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04735skim.root");*/\
worms_test.Add("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04733skim.root");\
worms_test.Add("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04731skim.root");\
worms_test.Add("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04729skim.root");\
worms_test.Add("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04727skim.root");\
worms_test.Add("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04725skim.root");\
worms_test.Add("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04723skim.root");\
worms_test.Add("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04721skim.root");\
worms_test.Add("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04719skim.root");\
worms_test.Add("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04717skim.root");\
worms_test.Add("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04715skim.root");\
worms_test.Add("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04713skim.root");\
worms_test.Add("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04711skim.root");\
worms_test.Add("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04709skim.root");\
worms_test.Add("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04707skim.root");\
worms_test.Add("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04705skim.root");\
worms_test.Add("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04703skim.root");\
worms_test.Add("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04701skim.root");\
worms_test.Add("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04699skim.root");\
worms_test.Add("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04697skim.root");\
worms_test.Add("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04695skim.root");\
worms_test.Add("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04693skim.root");\
worms_test.Add("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04605skim.root");\
/*worms_test.Add("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04603skim.root");*/\
worms_test.Add("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04557skim.root");\
worms_test.Add("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04555skim.root");\
worms_test.Add("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04521skim.root");\
worms_test.Add("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04475skim.root");\
worms_test.Add("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04473skim.root");\
worms_test.Add("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04471skim.root");\
/*worms_test.Add("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04469skim.root");*/\
worms_test.Add("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04467skim.root");\
worms_test.Add("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04424skim.root");\
/*worms_test.Add("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04377skim.root");*/\
worms_test.Add("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04375skim.root");\
/*worms_test.Add("/net/zwicky/dmtpc/production_beta/skimout/skim/dmtpc_10L_04333skim.root")*/;

#define WR5_TRAIN_OLD    \
/*worms.push_back("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_05102skim.root");*/\
/*worms.push_back("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_05100skim.root");*/\
/*worms.push_back("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_05048skim.root");*/\
worms.push_back("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04991skim.root");\
worms.push_back("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04989skim.root");\
worms.push_back("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04917skim.root");\
worms.push_back("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04854skim.root");\
worms.push_back("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04852skim.root");\
/*worms.push_back("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04791skim.root");*/\
worms.push_back("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04789skim.root");\
worms.push_back("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04742skim.root");\
worms.push_back("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04740skim.root");\
worms.push_back("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04738skim.root");\
worms.push_back("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04736skim.root");\
worms.push_back("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04734skim.root");\
worms.push_back("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04732skim.root");\
worms.push_back("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04730skim.root");\
/*worms.push_back("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04728skim.root");*/\
worms.push_back("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04726skim.root");\
worms.push_back("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04724skim.root");\
worms.push_back("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04722skim.root");\
worms.push_back("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04720skim.root");\
/*worms.push_back("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04718skim.root");*/\
worms.push_back("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04716skim.root");\
worms.push_back("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04714skim.root");\
worms.push_back("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04712skim.root");\
worms.push_back("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04710skim.root");\
worms.push_back("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04708skim.root");\
/*worms.push_back("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04706skim.root");*/\
worms.push_back("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04704skim.root");\
worms.push_back("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04702skim.root");\
worms.push_back("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04700skim.root");\
/*worms.push_back("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04698skim.root");*/\
worms.push_back("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04696skim.root");\
/*worms.push_back("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04694skim.root");*/\
worms.push_back("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04692skim.root");\
worms.push_back("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04604skim.root");\
worms.push_back("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04602skim.root");\
worms.push_back("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04556skim.root");\
worms.push_back("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04522skim.root");\
worms.push_back("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04520skim.root");\
worms.push_back("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04474skim.root");\
/*worms.push_back("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04472skim.root");*/\
worms.push_back("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04470skim.root");\
worms.push_back("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04468skim.root");\
worms.push_back("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04425skim.root");\
/*worms.push_back("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04423skim.root");*/\
worms.push_back("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04376skim.root");\
/*worms.push_back("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04334skim.root")*/;


#define WR5_TEST_OLD \
/*worms_test.Add("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04332skim.root");*/\
/*worms_test.Add("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_05101skim.root");*/\
/*worms_test.Add("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_05049skim.root");*/\
/*worms_test.Add("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_05047skim.root");*/\
worms_test.Add("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04990skim.root");\
worms_test.Add("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04918skim.root");\
/*worms_test.Add("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04916skim.root");*/\
worms_test.Add("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04853skim.root");\
worms_test.Add("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04851skim.root");\
worms_test.Add("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04790skim.root");\
/*worms_test.Add("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04788skim.root");*/\
worms_test.Add("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04741skim.root");\
worms_test.Add("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04739skim.root");\
worms_test.Add("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04737skim.root");\
/*worms_test.Add("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04735skim.root");*/\
worms_test.Add("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04733skim.root");\
worms_test.Add("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04731skim.root");\
worms_test.Add("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04729skim.root");\
worms_test.Add("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04727skim.root");\
worms_test.Add("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04725skim.root");\
worms_test.Add("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04723skim.root");\
worms_test.Add("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04721skim.root");\
worms_test.Add("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04719skim.root");\
worms_test.Add("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04717skim.root");\
worms_test.Add("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04715skim.root");\
worms_test.Add("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04713skim.root");\
worms_test.Add("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04711skim.root");\
worms_test.Add("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04709skim.root");\
worms_test.Add("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04707skim.root");\
worms_test.Add("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04705skim.root");\
worms_test.Add("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04703skim.root");\
worms_test.Add("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04701skim.root");\
worms_test.Add("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04699skim.root");\
worms_test.Add("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04697skim.root");\
worms_test.Add("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04695skim.root");\
worms_test.Add("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04693skim.root");\
worms_test.Add("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04605skim.root");\
/*worms_test.Add("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04603skim.root");*/\
worms_test.Add("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04557skim.root");\
worms_test.Add("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04555skim.root");\
worms_test.Add("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04521skim.root");\
worms_test.Add("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04475skim.root");\
worms_test.Add("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04473skim.root");\
worms_test.Add("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04471skim.root");\
/*worms_test.Add("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04469skim.root");*/\
worms_test.Add("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04467skim.root");\
worms_test.Add("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04424skim.root");\
/*worms_test.Add("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04377skim.root");*/\
worms_test.Add("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04375skim.root");\
/*worms_test.Add("/net/termite/raid1/dmtpc/production/skimout/skim/dmtpc_10L_04333skim.root")*/;
