/********************************************************************
* DmtpcPMTQECint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error DmtpcPMTQECint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableDmtpcPMTQECint();
extern void G__cpp_setup_inheritanceDmtpcPMTQECint();
extern void G__cpp_setup_typetableDmtpcPMTQECint();
extern void G__cpp_setup_memvarDmtpcPMTQECint();
extern void G__cpp_setup_globalDmtpcPMTQECint();
extern void G__cpp_setup_memfuncDmtpcPMTQECint();
extern void G__cpp_setup_funcDmtpcPMTQECint();
extern void G__set_cpp_environmentDmtpcPMTQECint();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "DmtpcPMTQE.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__DmtpcPMTQECintLN_TClass;
extern G__linked_taginfo G__DmtpcPMTQECintLN_TBuffer;
extern G__linked_taginfo G__DmtpcPMTQECintLN_TMemberInspector;
extern G__linked_taginfo G__DmtpcPMTQECintLN_TObject;
extern G__linked_taginfo G__DmtpcPMTQECintLN_TNamed;
extern G__linked_taginfo G__DmtpcPMTQECintLN_TString;
extern G__linked_taginfo G__DmtpcPMTQECintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__DmtpcPMTQECintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DmtpcPMTQECintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__DmtpcPMTQECintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DmtpcPMTQECintLN_TAttLine;
extern G__linked_taginfo G__DmtpcPMTQECintLN_TAttFill;
extern G__linked_taginfo G__DmtpcPMTQECintLN_TAttMarker;
extern G__linked_taginfo G__DmtpcPMTQECintLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__DmtpcPMTQECintLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__DmtpcPMTQECintLN_TGraph;
extern G__linked_taginfo G__DmtpcPMTQECintLN_TRandom3;
extern G__linked_taginfo G__DmtpcPMTQECintLN_DmtpcPMTQE;

/* STUB derived class for protected member access */
