//
// File generated by rootcint at Fri Jul 15 15:53:43 2016

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME DmtpcKeysCint
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "DmtpcKeysCint.h"

#include "TCollectionProxyInfo.h"
#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void DmtpcKeys_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void delete_DmtpcKeys(void *p);
   static void deleteArray_DmtpcKeys(void *p);
   static void destruct_DmtpcKeys(void *p);
   static void streamer_DmtpcKeys(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::DmtpcKeys*)
   {
      ::DmtpcKeys *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::DmtpcKeys >(0);
      static ::ROOT::TGenericClassInfo 
         instance("DmtpcKeys", ::DmtpcKeys::Class_Version(), "./DmtpcKeys.hh", 16,
                  typeid(::DmtpcKeys), DefineBehavior(ptr, ptr),
                  &::DmtpcKeys::Dictionary, isa_proxy, 0,
                  sizeof(::DmtpcKeys) );
      instance.SetDelete(&delete_DmtpcKeys);
      instance.SetDeleteArray(&deleteArray_DmtpcKeys);
      instance.SetDestructor(&destruct_DmtpcKeys);
      instance.SetStreamerFunc(&streamer_DmtpcKeys);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::DmtpcKeys*)
   {
      return GenerateInitInstanceLocal((::DmtpcKeys*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::DmtpcKeys*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *DmtpcKeys::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *DmtpcKeys::Class_Name()
{
   return "DmtpcKeys";
}

//______________________________________________________________________________
const char *DmtpcKeys::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::DmtpcKeys*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int DmtpcKeys::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::DmtpcKeys*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void DmtpcKeys::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::DmtpcKeys*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *DmtpcKeys::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::DmtpcKeys*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void DmtpcKeys::Streamer(TBuffer &R__b)
{
   // Stream an object of class DmtpcKeys.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      TObject::Streamer(R__b);
      {
         vector<TString> &R__stl =  _keys;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            TString R__t;
            R__t.Streamer(R__b);
            R__stl.push_back(R__t);
         }
      }
      {
         vector<TString> &R__stl =  _keydir;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            TString R__t;
            R__t.Streamer(R__b);
            R__stl.push_back(R__t);
         }
      }
      {
         vector<TString> &R__stl =  _files;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            TString R__t;
            R__t.Streamer(R__b);
            R__stl.push_back(R__t);
         }
      }
      _rootdirname.Streamer(R__b);
      _keyfilename.Streamer(R__b);
      _key.Streamer(R__b);
      _keynewdir.Streamer(R__b);
      R__b >> _isSkim;
      R__b >> _skimindex;
      R__b.CheckByteCount(R__s, R__c, DmtpcKeys::IsA());
   } else {
      R__c = R__b.WriteVersion(DmtpcKeys::IsA(), kTRUE);
      TObject::Streamer(R__b);
      {
         vector<TString> &R__stl =  _keys;
         int R__n=(&R__stl) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            vector<TString>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            ((TString&)(*R__k)).Streamer(R__b);
            }
         }
      }
      {
         vector<TString> &R__stl =  _keydir;
         int R__n=(&R__stl) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            vector<TString>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            ((TString&)(*R__k)).Streamer(R__b);
            }
         }
      }
      {
         vector<TString> &R__stl =  _files;
         int R__n=(&R__stl) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            vector<TString>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            ((TString&)(*R__k)).Streamer(R__b);
            }
         }
      }
      _rootdirname.Streamer(R__b);
      _keyfilename.Streamer(R__b);
      _key.Streamer(R__b);
      _keynewdir.Streamer(R__b);
      R__b << _isSkim;
      R__b << _skimindex;
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void DmtpcKeys::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class DmtpcKeys.
      TClass *R__cl = ::DmtpcKeys::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "_keys", (void*)&_keys);
      R__insp.InspectMember("vector<TString>", (void*)&_keys, "_keys.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "_keydir", (void*)&_keydir);
      R__insp.InspectMember("vector<TString>", (void*)&_keydir, "_keydir.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "_files", (void*)&_files);
      R__insp.InspectMember("vector<TString>", (void*)&_files, "_files.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "_rootdirname", &_rootdirname);
      R__insp.InspectMember(_rootdirname, "_rootdirname.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "_keyfilename", &_keyfilename);
      R__insp.InspectMember(_keyfilename, "_keyfilename.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "_key", &_key);
      R__insp.InspectMember(_key, "_key.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "_keynewdir", &_keynewdir);
      R__insp.InspectMember(_keynewdir, "_keynewdir.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "_isSkim", &_isSkim);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "_skimindex", &_skimindex);
      TObject::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrapper around operator delete
   static void delete_DmtpcKeys(void *p) {
      delete ((::DmtpcKeys*)p);
   }
   static void deleteArray_DmtpcKeys(void *p) {
      delete [] ((::DmtpcKeys*)p);
   }
   static void destruct_DmtpcKeys(void *p) {
      typedef ::DmtpcKeys current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_DmtpcKeys(TBuffer &buf, void *obj) {
      ((::DmtpcKeys*)obj)->::DmtpcKeys::Streamer(buf);
   }
} // end of namespace ROOT for class ::DmtpcKeys

namespace ROOT {
   void vectorlETStringgR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void vectorlETStringgR_Dictionary();
   static void *new_vectorlETStringgR(void *p = 0);
   static void *newArray_vectorlETStringgR(Long_t size, void *p);
   static void delete_vectorlETStringgR(void *p);
   static void deleteArray_vectorlETStringgR(void *p);
   static void destruct_vectorlETStringgR(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const vector<TString>*)
   {
      vector<TString> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<TString>),0);
      static ::ROOT::TGenericClassInfo 
         instance("vector<TString>", -2, "prec_stl/vector", 49,
                  typeid(vector<TString>), DefineBehavior(ptr, ptr),
                  0, &vectorlETStringgR_Dictionary, isa_proxy, 0,
                  sizeof(vector<TString>) );
      instance.SetNew(&new_vectorlETStringgR);
      instance.SetNewArray(&newArray_vectorlETStringgR);
      instance.SetDelete(&delete_vectorlETStringgR);
      instance.SetDeleteArray(&deleteArray_vectorlETStringgR);
      instance.SetDestructor(&destruct_vectorlETStringgR);
      instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::Pushback< vector<TString> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const vector<TString>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void vectorlETStringgR_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const vector<TString>*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   // Wrappers around operator new
   static void *new_vectorlETStringgR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<TString> : new vector<TString>;
   }
   static void *newArray_vectorlETStringgR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<TString>[nElements] : new vector<TString>[nElements];
   }
   // Wrapper around operator delete
   static void delete_vectorlETStringgR(void *p) {
      delete ((vector<TString>*)p);
   }
   static void deleteArray_vectorlETStringgR(void *p) {
      delete [] ((vector<TString>*)p);
   }
   static void destruct_vectorlETStringgR(void *p) {
      typedef vector<TString> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class vector<TString>

/********************************************************
* DmtpcKeysCint.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableDmtpcKeysCint();

extern "C" void G__set_cpp_environmentDmtpcKeysCint() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("DmtpcKeys.hh");
  G__cpp_reset_tagtableDmtpcKeysCint();
}
#include <new>
extern "C" int G__cpp_dllrevDmtpcKeysCint() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* DmtpcKeys */
static int G__DmtpcKeysCint_517_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   DmtpcKeys* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 7
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new DmtpcKeys(
*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, *((TString*) G__int(libp->para[2])), *((TString*) G__int(libp->para[3]))
, (int) G__int(libp->para[4]), (TString*) G__int(libp->para[5])
, *(bool*) G__Boolref(&libp->para[6]));
   } else {
     p = new((void*) gvp) DmtpcKeys(
*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, *((TString*) G__int(libp->para[2])), *((TString*) G__int(libp->para[3]))
, (int) G__int(libp->para[4]), (TString*) G__int(libp->para[5])
, *(bool*) G__Boolref(&libp->para[6]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__DmtpcKeysCintLN_DmtpcKeys));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcKeysCint_517_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((DmtpcKeys*) G__getstructoffset())->getNKeys());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcKeysCint_517_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((DmtpcKeys*) G__getstructoffset())->getNFiles());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcKeysCint_517_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         TString* pobj;
         TString xobj = ((DmtpcKeys*) G__getstructoffset())->getKey((int) G__int(libp->para[0]));
         pobj = new TString(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcKeysCint_517_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         TString* pobj;
         TString xobj = ((DmtpcKeys*) G__getstructoffset())->getDir((int) G__int(libp->para[0]));
         pobj = new TString(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcKeysCint_517_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         TString* pobj;
         TString xobj = ((DmtpcKeys*) G__getstructoffset())->getFile((int) G__int(libp->para[0]));
         pobj = new TString(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcKeysCint_517_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<TString>* pobj;
         vector<TString> xobj = ((DmtpcKeys*) G__getstructoffset())->getListOfKeys();
         pobj = new vector<TString>(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcKeysCint_517_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<TString>* pobj;
         vector<TString> xobj = ((DmtpcKeys*) G__getstructoffset())->getListOfDirs();
         pobj = new vector<TString>(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcKeysCint_517_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<TString>* pobj;
         vector<TString> xobj = ((DmtpcKeys*) G__getstructoffset())->getListOfFiles();
         pobj = new vector<TString>(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcKeysCint_517_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         TString* pobj;
         TString xobj = ((DmtpcKeys*) G__getstructoffset())->getRootDirName();
         pobj = new TString(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcKeysCint_517_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((DmtpcKeys*) G__getstructoffset())->contains(*((TString*) G__int(libp->para[0]))));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcKeysCint_517_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((DmtpcKeys*) G__getstructoffset())->contains((int) G__int(libp->para[0]), (TString*) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcKeysCint_517_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((DmtpcKeys*) G__getstructoffset())->writeKey();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcKeysCint_517_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((DmtpcKeys*) G__getstructoffset())->addFriends((TTree*) G__int(libp->para[0]), (int) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcKeysCint_517_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((DmtpcKeys*) G__getstructoffset())->openOutputFile((TFile*) G__int(libp->para[0]), (int) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcKeysCint_517_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((DmtpcKeys*) G__getstructoffset())->isSkim());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcKeysCint_517_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((DmtpcKeys*) G__getstructoffset())->getBaseTree((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcKeysCint_517_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) DmtpcKeys::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcKeysCint_517_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) DmtpcKeys::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcKeysCint_517_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) DmtpcKeys::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcKeysCint_517_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      DmtpcKeys::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcKeysCint_517_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((DmtpcKeys*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcKeysCint_517_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) DmtpcKeys::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcKeysCint_517_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) DmtpcKeys::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcKeysCint_517_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) DmtpcKeys::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcKeysCint_517_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) DmtpcKeys::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__DmtpcKeysCint_517_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   DmtpcKeys* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new DmtpcKeys(*(DmtpcKeys*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__DmtpcKeysCintLN_DmtpcKeys));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef DmtpcKeys G__TDmtpcKeys;
static int G__DmtpcKeysCint_517_0_31(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (DmtpcKeys*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((DmtpcKeys*) (soff+(sizeof(DmtpcKeys)*i)))->~G__TDmtpcKeys();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (DmtpcKeys*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((DmtpcKeys*) (soff))->~G__TDmtpcKeys();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__DmtpcKeysCint_517_0_32(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   DmtpcKeys* dest = (DmtpcKeys*) G__getstructoffset();
   *dest = *(DmtpcKeys*) libp->para[0].ref;
   const DmtpcKeys& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* DmtpcKeys */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncDmtpcKeysCint {
 public:
  G__Sizep2memfuncDmtpcKeysCint(): p(&G__Sizep2memfuncDmtpcKeysCint::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncDmtpcKeysCint::*p)();
};

size_t G__get_sizep2memfuncDmtpcKeysCint()
{
  G__Sizep2memfuncDmtpcKeysCint a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceDmtpcKeysCint() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__DmtpcKeysCintLN_DmtpcKeys))) {
     DmtpcKeys *G__Lderived;
     G__Lderived=(DmtpcKeys*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__DmtpcKeysCintLN_DmtpcKeys),G__get_linked_tagnum(&G__DmtpcKeysCintLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableDmtpcKeysCint() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__DmtpcKeysCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__DmtpcKeysCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DmtpcKeysCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__DmtpcKeysCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DmtpcKeysCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__DmtpcKeysCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__DmtpcKeysCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DmtpcKeysCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__DmtpcKeysCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DmtpcKeysCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__DmtpcKeysCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__DmtpcKeysCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__DmtpcKeysCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__DmtpcKeysCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TObjArray*>",117,G__get_linked_tagnum(&G__DmtpcKeysCintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__DmtpcKeysCintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*,less<string> >",117,G__get_linked_tagnum(&G__DmtpcKeysCintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TString>",117,G__get_linked_tagnum(&G__DmtpcKeysCintLN_vectorlETStringcOallocatorlETStringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__DmtpcKeysCintLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DmtpcKeysCintLN_vectorlETStringcOallocatorlETStringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__DmtpcKeysCintLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DmtpcKeysCintLN_vectorlETStringcOallocatorlETStringgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* DmtpcKeys */
static void G__setup_memvarDmtpcKeys(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__DmtpcKeysCintLN_DmtpcKeys));
   { DmtpcKeys *p; p=(DmtpcKeys*)0x1000; if (p) { }
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__DmtpcKeysCintLN_vectorlETStringcOallocatorlETStringgRsPgR),G__defined_typename("vector<TString>"),-1,4,"_keys=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__DmtpcKeysCintLN_vectorlETStringcOallocatorlETStringgRsPgR),G__defined_typename("vector<TString>"),-1,4,"_keydir=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__DmtpcKeysCintLN_vectorlETStringcOallocatorlETStringgRsPgR),G__defined_typename("vector<TString>"),-1,4,"_files=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__DmtpcKeysCintLN_TString),-1,-1,4,"_rootdirname=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__DmtpcKeysCintLN_TString),-1,-1,4,"_keyfilename=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__DmtpcKeysCintLN_TString),-1,-1,4,"_key=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__DmtpcKeysCintLN_TString),-1,-1,4,"_keynewdir=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"_isSkim=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"_skimindex=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DmtpcKeysCintLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarDmtpcKeysCint() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncDmtpcKeys(void) {
   /* DmtpcKeys */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__DmtpcKeysCintLN_DmtpcKeys));
   G__memfunc_setup("DmtpcKeys",916,G__DmtpcKeysCint_517_0_1, 105, G__get_linked_tagnum(&G__DmtpcKeysCintLN_DmtpcKeys), -1, 0, 7, 1, 1, 0, 
"u 'TString' - 0 - keyfilename u 'TString' - 0 - rawdatafiles "
"u 'TString' - 0 - key u 'TString' - 0 - newdir "
"i - - 0 - nreqmod U 'TString' - 0 - reqmod "
"g - - 1 - pass", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getNKeys",810,G__DmtpcKeysCint_517_0_2, 105, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getNFiles",897,G__DmtpcKeysCint_517_0_3, 105, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getKey",617,G__DmtpcKeysCint_517_0_4, 117, G__get_linked_tagnum(&G__DmtpcKeysCintLN_TString), -1, 0, 1, 1, 1, 0, "i - - 0 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getDir",607,G__DmtpcKeysCint_517_0_5, 117, G__get_linked_tagnum(&G__DmtpcKeysCintLN_TString), -1, 0, 1, 1, 1, 0, "i - - 0 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getFile",704,G__DmtpcKeysCint_517_0_6, 117, G__get_linked_tagnum(&G__DmtpcKeysCintLN_TString), -1, 0, 1, 1, 1, 0, "i - - 0 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getListOfKeys",1325,G__DmtpcKeysCint_517_0_7, 117, G__get_linked_tagnum(&G__DmtpcKeysCintLN_vectorlETStringcOallocatorlETStringgRsPgR), G__defined_typename("vector<TString>"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getListOfDirs",1315,G__DmtpcKeysCint_517_0_8, 117, G__get_linked_tagnum(&G__DmtpcKeysCintLN_vectorlETStringcOallocatorlETStringgRsPgR), G__defined_typename("vector<TString>"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getListOfFiles",1412,G__DmtpcKeysCint_517_0_9, 117, G__get_linked_tagnum(&G__DmtpcKeysCintLN_vectorlETStringcOallocatorlETStringgRsPgR), G__defined_typename("vector<TString>"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getRootDirName",1412,G__DmtpcKeysCint_517_0_10, 117, G__get_linked_tagnum(&G__DmtpcKeysCintLN_TString), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("contains",863,G__DmtpcKeysCint_517_0_11, 103, -1, -1, 0, 1, 1, 1, 0, "u 'TString' - 0 - testkey", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("contains",863,G__DmtpcKeysCint_517_0_12, 103, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - n U 'TString' - 0 - testkeys", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("writeKey",852,G__DmtpcKeysCint_517_0_13, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("addFriends",1012,G__DmtpcKeysCint_517_0_14, 121, -1, -1, 0, 2, 1, 1, 0, 
"U 'TTree' - 0 - tree i - - 0 - f", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("openOutputFile",1475,G__DmtpcKeysCint_517_0_15, 103, -1, -1, 0, 2, 1, 1, 0, 
"U 'TFile' - 0 - routfile i - - 0 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("isSkim",624,G__DmtpcKeysCint_517_0_16, 103, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getBaseTree",1099,G__DmtpcKeysCint_517_0_17, 85, G__get_linked_tagnum(&G__DmtpcKeysCintLN_TTree), -1, 0, 1, 1, 1, 0, "i - - 0 - f", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__DmtpcKeysCint_517_0_18, 85, G__get_linked_tagnum(&G__DmtpcKeysCintLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&DmtpcKeys::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__DmtpcKeysCint_517_0_19, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&DmtpcKeys::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__DmtpcKeysCint_517_0_20, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&DmtpcKeys::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__DmtpcKeysCint_517_0_21, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&DmtpcKeys::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__DmtpcKeysCintLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - insp", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__DmtpcKeysCint_517_0_25, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__DmtpcKeysCint_517_0_26, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&DmtpcKeys::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__DmtpcKeysCint_517_0_27, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&DmtpcKeys::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__DmtpcKeysCint_517_0_28, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&DmtpcKeys::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__DmtpcKeysCint_517_0_29, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&DmtpcKeys::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("DmtpcKeys", 916, G__DmtpcKeysCint_517_0_30, (int) ('i'), G__get_linked_tagnum(&G__DmtpcKeysCintLN_DmtpcKeys), -1, 0, 1, 1, 1, 0, "u 'DmtpcKeys' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~DmtpcKeys", 1042, G__DmtpcKeysCint_517_0_31, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__DmtpcKeysCint_517_0_32, (int) ('u'), G__get_linked_tagnum(&G__DmtpcKeysCintLN_DmtpcKeys), -1, 1, 1, 1, 1, 0, "u 'DmtpcKeys' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncDmtpcKeysCint() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalDmtpcKeysCint() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcDmtpcKeysCint() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__DmtpcKeysCintLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__DmtpcKeysCintLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__DmtpcKeysCintLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__DmtpcKeysCintLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__DmtpcKeysCintLN_TString = { "TString" , 99 , -1 };
G__linked_taginfo G__DmtpcKeysCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__DmtpcKeysCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__DmtpcKeysCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__DmtpcKeysCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__DmtpcKeysCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__DmtpcKeysCintLN_TTree = { "TTree" , 99 , -1 };
G__linked_taginfo G__DmtpcKeysCintLN_TFile = { "TFile" , 99 , -1 };
G__linked_taginfo G__DmtpcKeysCintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR = { "map<string,TObjArray*,less<string>,allocator<pair<const string,TObjArray*> > >" , 99 , -1 };
G__linked_taginfo G__DmtpcKeysCintLN_DmtpcKeys = { "DmtpcKeys" , 99 , -1 };
G__linked_taginfo G__DmtpcKeysCintLN_vectorlETStringcOallocatorlETStringgRsPgR = { "vector<TString,allocator<TString> >" , 99 , -1 };
G__linked_taginfo G__DmtpcKeysCintLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TString,allocator<TString> >::iterator>" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableDmtpcKeysCint() {
  G__DmtpcKeysCintLN_TClass.tagnum = -1 ;
  G__DmtpcKeysCintLN_TBuffer.tagnum = -1 ;
  G__DmtpcKeysCintLN_TMemberInspector.tagnum = -1 ;
  G__DmtpcKeysCintLN_TObject.tagnum = -1 ;
  G__DmtpcKeysCintLN_TString.tagnum = -1 ;
  G__DmtpcKeysCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__DmtpcKeysCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__DmtpcKeysCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__DmtpcKeysCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__DmtpcKeysCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__DmtpcKeysCintLN_TTree.tagnum = -1 ;
  G__DmtpcKeysCintLN_TFile.tagnum = -1 ;
  G__DmtpcKeysCintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR.tagnum = -1 ;
  G__DmtpcKeysCintLN_DmtpcKeys.tagnum = -1 ;
  G__DmtpcKeysCintLN_vectorlETStringcOallocatorlETStringgRsPgR.tagnum = -1 ;
  G__DmtpcKeysCintLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableDmtpcKeysCint() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__DmtpcKeysCintLN_TClass);
   G__get_linked_tagnum_fwd(&G__DmtpcKeysCintLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__DmtpcKeysCintLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__DmtpcKeysCintLN_TObject);
   G__get_linked_tagnum_fwd(&G__DmtpcKeysCintLN_TString);
   G__get_linked_tagnum_fwd(&G__DmtpcKeysCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__DmtpcKeysCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__DmtpcKeysCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__DmtpcKeysCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__DmtpcKeysCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__DmtpcKeysCintLN_TTree);
   G__get_linked_tagnum_fwd(&G__DmtpcKeysCintLN_TFile);
   G__get_linked_tagnum_fwd(&G__DmtpcKeysCintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__DmtpcKeysCintLN_DmtpcKeys),sizeof(DmtpcKeys),-1,62464,(char*)NULL,G__setup_memvarDmtpcKeys,G__setup_memfuncDmtpcKeys);
   G__get_linked_tagnum_fwd(&G__DmtpcKeysCintLN_vectorlETStringcOallocatorlETStringgRsPgR);
   G__get_linked_tagnum_fwd(&G__DmtpcKeysCintLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR);
}
extern "C" void G__cpp_setupDmtpcKeysCint(void) {
  G__check_setup_version(30051515,"G__cpp_setupDmtpcKeysCint()");
  G__set_cpp_environmentDmtpcKeysCint();
  G__cpp_setup_tagtableDmtpcKeysCint();

  G__cpp_setup_inheritanceDmtpcKeysCint();

  G__cpp_setup_typetableDmtpcKeysCint();

  G__cpp_setup_memvarDmtpcKeysCint();

  G__cpp_setup_memfuncDmtpcKeysCint();
  G__cpp_setup_globalDmtpcKeysCint();
  G__cpp_setup_funcDmtpcKeysCint();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncDmtpcKeysCint();
  return;
}
class G__cpp_setup_initDmtpcKeysCint {
  public:
    G__cpp_setup_initDmtpcKeysCint() { G__add_setup_func("DmtpcKeysCint",(G__incsetup)(&G__cpp_setupDmtpcKeysCint)); G__call_setup_funcs(); }
   ~G__cpp_setup_initDmtpcKeysCint() { G__remove_setup_func("DmtpcKeysCint"); }
};
G__cpp_setup_initDmtpcKeysCint G__cpp_setup_initializerDmtpcKeysCint;

