/********************************************************************
* DmtpcGainMapCint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error DmtpcGainMapCint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableDmtpcGainMapCint();
extern void G__cpp_setup_inheritanceDmtpcGainMapCint();
extern void G__cpp_setup_typetableDmtpcGainMapCint();
extern void G__cpp_setup_memvarDmtpcGainMapCint();
extern void G__cpp_setup_globalDmtpcGainMapCint();
extern void G__cpp_setup_memfuncDmtpcGainMapCint();
extern void G__cpp_setup_funcDmtpcGainMapCint();
extern void G__set_cpp_environmentDmtpcGainMapCint();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "DmtpcGainMap.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__DmtpcGainMapCintLN_TClass;
extern G__linked_taginfo G__DmtpcGainMapCintLN_TBuffer;
extern G__linked_taginfo G__DmtpcGainMapCintLN_TMemberInspector;
extern G__linked_taginfo G__DmtpcGainMapCintLN_TObject;
extern G__linked_taginfo G__DmtpcGainMapCintLN_TNamed;
extern G__linked_taginfo G__DmtpcGainMapCintLN_TString;
extern G__linked_taginfo G__DmtpcGainMapCintLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__DmtpcGainMapCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__DmtpcGainMapCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DmtpcGainMapCintLN_TObjArray;
extern G__linked_taginfo G__DmtpcGainMapCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__DmtpcGainMapCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DmtpcGainMapCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__DmtpcGainMapCintLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__DmtpcGainMapCintLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__DmtpcGainMapCintLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__DmtpcGainMapCintLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__DmtpcGainMapCintLN_TH2F;
extern G__linked_taginfo G__DmtpcGainMapCintLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__DmtpcGainMapCintLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__DmtpcGainMapCintLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__DmtpcGainMapCintLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__DmtpcGainMapCintLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__DmtpcGainMapCintLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__DmtpcGainMapCintLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__DmtpcGainMapCintLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__DmtpcGainMapCintLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__DmtpcGainMapCintLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__DmtpcGainMapCintLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__DmtpcGainMapCintLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__DmtpcGainMapCintLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__DmtpcGainMapCintLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__DmtpcGainMapCintLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__DmtpcGainMapCintLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__DmtpcGainMapCintLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__DmtpcGainMapCintLN_TVector3;
extern G__linked_taginfo G__DmtpcGainMapCintLN_DmtpcGainMap;
extern G__linked_taginfo G__DmtpcGainMapCintLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__DmtpcGainMapCintLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
