//
// File generated by rootcint at Tue Jul 12 17:20:44 2016

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME DmtpcDataConverterCint
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "DmtpcDataConverterCint.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace DmtpcDataConverter {
   namespace ROOT {
      inline ::ROOT::TGenericClassInfo *GenerateInitInstance();
      static void DmtpcDataConverter_Dictionary();

      // Function generating the singleton type initializer
      inline ::ROOT::TGenericClassInfo *GenerateInitInstance()
      {
         static ::ROOT::TGenericClassInfo 
            instance("DmtpcDataConverter", 0 /*version*/, "./DmtpcDataConverter.hh", 21,
                     ::ROOT::DefineBehavior((void*)0,(void*)0),
                     &DmtpcDataConverter_Dictionary, 0);
         return &instance;
      }
      // Insure that the inline function is _not_ optimized away by the compiler
      ::ROOT::TGenericClassInfo *(*_R__UNIQUE_(InitFunctionKeeper))() = &GenerateInitInstance;  
      // Static variable to force the class initialization
      static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstance(); R__UseDummy(_R__UNIQUE_(Init));

      // Dictionary for non-ClassDef classes
      static void DmtpcDataConverter_Dictionary() {
         GenerateInitInstance()->GetClass();
      }

   }
}

/********************************************************
* DmtpcDataConverterCint.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableDmtpcDataConverterCint();

extern "C" void G__set_cpp_environmentDmtpcDataConverterCint() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("DmtpcDataConverter.hh");
  G__cpp_reset_tagtableDmtpcDataConverterCint();
}
#include <new>
extern "C" int G__cpp_dllrevDmtpcDataConverterCint() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* DmtpcDataConverter */
static int G__DmtpcDataConverterCint_691_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      G__letint(result7, 85, (long) DmtpcDataConverter::convertHistDataTypes((DmtpcEvent*) G__int(libp->para[0]), (DmtpcEvent*) G__int(libp->para[1])));
      break;
   case 1:
      G__letint(result7, 85, (long) DmtpcDataConverter::convertHistDataTypes((DmtpcEvent*) G__int(libp->para[0])));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcDataConverterCint_691_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 3:
      DmtpcDataConverter::convertDataFile((const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1])
, (bool) G__int(libp->para[2]));
      G__setnull(result7);
      break;
   case 2:
      DmtpcDataConverter::convertDataFile((const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1]));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcDataConverterCint_691_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 4:
      G__letint(result7, 85, (long) DmtpcDataConverter::scopeReduce((TH1F*) G__int(libp->para[0]), (ScopeDataInfo*) G__int(libp->para[1])
, (const char*) G__int(libp->para[2]), (TH1F*) G__int(libp->para[3])));
      break;
   case 3:
      G__letint(result7, 85, (long) DmtpcDataConverter::scopeReduce((TH1F*) G__int(libp->para[0]), (ScopeDataInfo*) G__int(libp->para[1])
, (const char*) G__int(libp->para[2])));
      break;
   case 2:
      G__letint(result7, 85, (long) DmtpcDataConverter::scopeReduce((TH1F*) G__int(libp->para[0]), (ScopeDataInfo*) G__int(libp->para[1])));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcDataConverterCint_691_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 3:
      G__letint(result7, 85, (long) DmtpcDataConverter::ccdReduce((TH2F*) G__int(libp->para[0]), (const char*) G__int(libp->para[1])
, (TH2S*) G__int(libp->para[2])));
      break;
   case 2:
      G__letint(result7, 85, (long) DmtpcDataConverter::ccdReduce((TH2F*) G__int(libp->para[0]), (const char*) G__int(libp->para[1])));
      break;
   case 1:
      G__letint(result7, 85, (long) DmtpcDataConverter::ccdReduce((TH2F*) G__int(libp->para[0])));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcDataConverterCint_691_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 3:
      G__letint(result7, 85, (long) DmtpcDataConverter::scopeExpand((ScopeWaveformData*) G__int(libp->para[0]), (const char*) G__int(libp->para[1])
, (TH1F*) G__int(libp->para[2])));
      break;
   case 2:
      G__letint(result7, 85, (long) DmtpcDataConverter::scopeExpand((ScopeWaveformData*) G__int(libp->para[0]), (const char*) G__int(libp->para[1])));
      break;
   case 1:
      G__letint(result7, 85, (long) DmtpcDataConverter::scopeExpand((ScopeWaveformData*) G__int(libp->para[0])));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcDataConverterCint_691_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 3:
      G__letint(result7, 85, (long) DmtpcDataConverter::ccdExpand((TH2S*) G__int(libp->para[0]), (const char*) G__int(libp->para[1])
, (TH2F*) G__int(libp->para[2])));
      break;
   case 2:
      G__letint(result7, 85, (long) DmtpcDataConverter::ccdExpand((TH2S*) G__int(libp->para[0]), (const char*) G__int(libp->para[1])));
      break;
   case 1:
      G__letint(result7, 85, (long) DmtpcDataConverter::ccdExpand((TH2S*) G__int(libp->para[0])));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* DmtpcDataConverter */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncDmtpcDataConverterCint {
 public:
  G__Sizep2memfuncDmtpcDataConverterCint(): p(&G__Sizep2memfuncDmtpcDataConverterCint::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncDmtpcDataConverterCint::*p)();
};

size_t G__get_sizep2memfuncDmtpcDataConverterCint()
{
  G__Sizep2memfuncDmtpcDataConverterCint a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceDmtpcDataConverterCint() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableDmtpcDataConverterCint() {

   /* Setting up typedef entry */
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__DmtpcDataConverterCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__DmtpcDataConverterCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DmtpcDataConverterCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__DmtpcDataConverterCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DmtpcDataConverterCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__DmtpcDataConverterCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__DmtpcDataConverterCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DmtpcDataConverterCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__DmtpcDataConverterCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DmtpcDataConverterCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__DmtpcDataConverterCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__DmtpcDataConverterCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__DmtpcDataConverterCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__DmtpcDataConverterCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TObjArray*>",117,G__get_linked_tagnum(&G__DmtpcDataConverterCintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__DmtpcDataConverterCintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*,less<string> >",117,G__get_linked_tagnum(&G__DmtpcDataConverterCintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__DmtpcDataConverterCintLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__DmtpcDataConverterCintLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__DmtpcDataConverterCintLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__DmtpcDataConverterCintLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<SimpleConfigStore_t>",117,G__get_linked_tagnum(&G__DmtpcDataConverterCintLN_vectorlESimpleConfigStore_tcOallocatorlESimpleConfigStore_tgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__DmtpcDataConverterCintLN_reverse_iteratorlEvectorlESimpleConfigStore_tcOallocatorlESimpleConfigStore_tgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DmtpcDataConverterCintLN_vectorlESimpleConfigStore_tcOallocatorlESimpleConfigStore_tgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__DmtpcDataConverterCintLN_reverse_iteratorlEvectorlESimpleConfigStore_tcOallocatorlESimpleConfigStore_tgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DmtpcDataConverterCintLN_vectorlESimpleConfigStore_tcOallocatorlESimpleConfigStore_tgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<UInt_t>",117,G__get_linked_tagnum(&G__DmtpcDataConverterCintLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TString>",117,G__get_linked_tagnum(&G__DmtpcDataConverterCintLN_vectorlETStringcOallocatorlETStringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__DmtpcDataConverterCintLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DmtpcDataConverterCintLN_vectorlETStringcOallocatorlETStringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__DmtpcDataConverterCintLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DmtpcDataConverterCintLN_vectorlETStringcOallocatorlETStringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TH2F*>",117,G__get_linked_tagnum(&G__DmtpcDataConverterCintLN_vectorlETH2FmUcOallocatorlETH2FmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__DmtpcDataConverterCintLN_reverse_iteratorlEvectorlETH2FmUcOallocatorlETH2FmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DmtpcDataConverterCintLN_vectorlETH2FmUcOallocatorlETH2FmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__DmtpcDataConverterCintLN_reverse_iteratorlEvectorlETH2FmUcOallocatorlETH2FmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DmtpcDataConverterCintLN_vectorlETH2FmUcOallocatorlETH2FmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TH1F*>",117,G__get_linked_tagnum(&G__DmtpcDataConverterCintLN_vectorlETH1FmUcOallocatorlETH1FmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__DmtpcDataConverterCintLN_reverse_iteratorlEvectorlETH1FmUcOallocatorlETH1FmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DmtpcDataConverterCintLN_vectorlETH1FmUcOallocatorlETH1FmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__DmtpcDataConverterCintLN_reverse_iteratorlEvectorlETH1FmUcOallocatorlETH1FmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DmtpcDataConverterCintLN_vectorlETH1FmUcOallocatorlETH1FmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixT<Float_t>",117,G__get_linked_tagnum(&G__DmtpcDataConverterCintLN_TMatrixTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow_const<Float_t>",117,G__get_linked_tagnum(&G__DmtpcDataConverterCintLN_TMatrixTRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn_const<Float_t>",117,G__get_linked_tagnum(&G__DmtpcDataConverterCintLN_TMatrixTColumn_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag_const<Float_t>",117,G__get_linked_tagnum(&G__DmtpcDataConverterCintLN_TMatrixTDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat_const<Float_t>",117,G__get_linked_tagnum(&G__DmtpcDataConverterCintLN_TMatrixTFlat_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub_const<Float_t>",117,G__get_linked_tagnum(&G__DmtpcDataConverterCintLN_TMatrixTSub_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow_const<Float_t>",117,G__get_linked_tagnum(&G__DmtpcDataConverterCintLN_TMatrixTSparseRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag_const<Float_t>",117,G__get_linked_tagnum(&G__DmtpcDataConverterCintLN_TMatrixTSparseDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow<Float_t>",117,G__get_linked_tagnum(&G__DmtpcDataConverterCintLN_TMatrixTRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn<Float_t>",117,G__get_linked_tagnum(&G__DmtpcDataConverterCintLN_TMatrixTColumnlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag<Float_t>",117,G__get_linked_tagnum(&G__DmtpcDataConverterCintLN_TMatrixTDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat<Float_t>",117,G__get_linked_tagnum(&G__DmtpcDataConverterCintLN_TMatrixTFlatlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub<Float_t>",117,G__get_linked_tagnum(&G__DmtpcDataConverterCintLN_TMatrixTSublEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow<Float_t>",117,G__get_linked_tagnum(&G__DmtpcDataConverterCintLN_TMatrixTSparseRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag<Float_t>",117,G__get_linked_tagnum(&G__DmtpcDataConverterCintLN_TMatrixTSparseDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementActionT<Float_t>",117,G__get_linked_tagnum(&G__DmtpcDataConverterCintLN_TElementActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementPosActionT<Float_t>",117,G__get_linked_tagnum(&G__DmtpcDataConverterCintLN_TElementPosActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* DmtpcDataConverter */
static void G__setup_memvarDmtpcDataConverter(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__DmtpcDataConverterCintLN_DmtpcDataConverter));
   {
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarDmtpcDataConverterCint() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncDmtpcDataConverter(void) {
   /* DmtpcDataConverter */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__DmtpcDataConverterCintLN_DmtpcDataConverter));
   G__memfunc_setup("convertHistDataTypes",2088,G__DmtpcDataConverterCint_691_0_1, 85, G__get_linked_tagnum(&G__DmtpcDataConverterCintLN_DmtpcEvent), -1, 0, 2, 1, 1, 0, 
"U 'DmtpcEvent' - 0 - old U 'DmtpcEvent' - 0 'NULL' placement_ptr", (char*)NULL, (void*) G__func2void( (DmtpcEvent* (*)(DmtpcEvent*, DmtpcEvent*))(&DmtpcDataConverter::convertHistDataTypes) ), 0);
   G__memfunc_setup("convertDataFile",1531,G__DmtpcDataConverterCint_691_0_2, 121, -1, -1, 0, 3, 1, 1, 0, 
"C - - 10 - infile C - - 10 - outfile "
"g - - 0 'true' overwrite", (char*)NULL, (void*) G__func2void( (void (*)(const char*, const char*, bool))(&DmtpcDataConverter::convertDataFile) ), 0);
   G__memfunc_setup("scopeReduce",1138,G__DmtpcDataConverterCint_691_0_3, 85, G__get_linked_tagnum(&G__DmtpcDataConverterCintLN_ScopeWaveformData), -1, 0, 4, 1, 1, 0, 
"U 'TH1F' - 10 - old U 'ScopeDataInfo' - 10 - sinfo "
"C - - 10 'NULL' new_name U 'TH1F' - 0 'NULL' placement_ptr", (char*)NULL, (void*) G__func2void( (ScopeWaveformData* (*)(const TH1F*, const ScopeDataInfo*, const char*, TH1F*))(&DmtpcDataConverter::scopeReduce) ), 0);
   G__memfunc_setup("ccdReduce",898,G__DmtpcDataConverterCint_691_0_4, 85, G__get_linked_tagnum(&G__DmtpcDataConverterCintLN_TH2S), -1, 0, 3, 1, 1, 0, 
"U 'TH2F' - 10 - old C - - 10 'NULL' new_name "
"U 'TH2S' - 0 'NULL' placement_ptr", (char*)NULL, (void*) G__func2void( (TH2S* (*)(const TH2F*, const char*, TH2S*))(&DmtpcDataConverter::ccdReduce) ), 0);
   G__memfunc_setup("scopeExpand",1146,G__DmtpcDataConverterCint_691_0_5, 85, G__get_linked_tagnum(&G__DmtpcDataConverterCintLN_TH1F), -1, 0, 3, 1, 1, 0, 
"U 'ScopeWaveformData' - 10 - reduced C - - 10 'NULL' new_name "
"U 'TH1F' - 0 'NULL' placement_ptr", (char*)NULL, (void*) G__func2void( (TH1F* (*)(const ScopeWaveformData*, const char*, TH1F*))(&DmtpcDataConverter::scopeExpand) ), 0);
   G__memfunc_setup("ccdExpand",906,G__DmtpcDataConverterCint_691_0_6, 85, G__get_linked_tagnum(&G__DmtpcDataConverterCintLN_TH2F), -1, 0, 3, 1, 1, 0, 
"U 'TH2S' - 10 - reduced C - - 10 'NULL' new_name "
"U 'TH2F' - 0 'NULL' placement_ptr", (char*)NULL, (void*) G__func2void( (TH2F* (*)(const TH2S*, const char*, TH2F*))(&DmtpcDataConverter::ccdExpand) ), 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncDmtpcDataConverterCint() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {
}

static void G__cpp_setup_global5() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalDmtpcDataConverterCint() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
  G__cpp_setup_global5();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcDmtpcDataConverterCint() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__DmtpcDataConverterCintLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR = { "vector<unsigned int,allocator<unsigned int> >" , 99 , -1 };
G__linked_taginfo G__DmtpcDataConverterCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__DmtpcDataConverterCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__DmtpcDataConverterCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__DmtpcDataConverterCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__DmtpcDataConverterCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__DmtpcDataConverterCintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR = { "map<string,TObjArray*,less<string>,allocator<pair<const string,TObjArray*> > >" , 99 , -1 };
G__linked_taginfo G__DmtpcDataConverterCintLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__DmtpcDataConverterCintLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__DmtpcDataConverterCintLN_TH1F = { "TH1F" , 99 , -1 };
G__linked_taginfo G__DmtpcDataConverterCintLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__DmtpcDataConverterCintLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__DmtpcDataConverterCintLN_TH2S = { "TH2S" , 99 , -1 };
G__linked_taginfo G__DmtpcDataConverterCintLN_TH2F = { "TH2F" , 99 , -1 };
G__linked_taginfo G__DmtpcDataConverterCintLN_ScopeWaveformData = { "ScopeWaveformData" , 99 , -1 };
G__linked_taginfo G__DmtpcDataConverterCintLN_vectorlESimpleConfigStore_tcOallocatorlESimpleConfigStore_tgRsPgR = { "vector<SimpleConfigStore_t,allocator<SimpleConfigStore_t> >" , 99 , -1 };
G__linked_taginfo G__DmtpcDataConverterCintLN_reverse_iteratorlEvectorlESimpleConfigStore_tcOallocatorlESimpleConfigStore_tgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<SimpleConfigStore_t,allocator<SimpleConfigStore_t> >::iterator>" , 99 , -1 };
G__linked_taginfo G__DmtpcDataConverterCintLN_vectorlETStringcOallocatorlETStringgRsPgR = { "vector<TString,allocator<TString> >" , 99 , -1 };
G__linked_taginfo G__DmtpcDataConverterCintLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TString,allocator<TString> >::iterator>" , 99 , -1 };
G__linked_taginfo G__DmtpcDataConverterCintLN_ScopeDataInfo = { "ScopeDataInfo" , 99 , -1 };
G__linked_taginfo G__DmtpcDataConverterCintLN_DmtpcEvent = { "DmtpcEvent" , 99 , -1 };
G__linked_taginfo G__DmtpcDataConverterCintLN_vectorlETH2FmUcOallocatorlETH2FmUgRsPgR = { "vector<TH2F*,allocator<TH2F*> >" , 99 , -1 };
G__linked_taginfo G__DmtpcDataConverterCintLN_reverse_iteratorlEvectorlETH2FmUcOallocatorlETH2FmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TH2F*,allocator<TH2F*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__DmtpcDataConverterCintLN_vectorlETH1FmUcOallocatorlETH1FmUgRsPgR = { "vector<TH1F*,allocator<TH1F*> >" , 99 , -1 };
G__linked_taginfo G__DmtpcDataConverterCintLN_reverse_iteratorlEvectorlETH1FmUcOallocatorlETH1FmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TH1F*,allocator<TH1F*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__DmtpcDataConverterCintLN_TElementActionTlEfloatgR = { "TElementActionT<float>" , 99 , -1 };
G__linked_taginfo G__DmtpcDataConverterCintLN_TElementPosActionTlEfloatgR = { "TElementPosActionT<float>" , 99 , -1 };
G__linked_taginfo G__DmtpcDataConverterCintLN_TMatrixTlEfloatgR = { "TMatrixT<float>" , 99 , -1 };
G__linked_taginfo G__DmtpcDataConverterCintLN_TMatrixTRow_constlEfloatgR = { "TMatrixTRow_const<float>" , 99 , -1 };
G__linked_taginfo G__DmtpcDataConverterCintLN_TMatrixTRowlEfloatgR = { "TMatrixTRow<float>" , 99 , -1 };
G__linked_taginfo G__DmtpcDataConverterCintLN_TMatrixTDiag_constlEfloatgR = { "TMatrixTDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__DmtpcDataConverterCintLN_TMatrixTColumn_constlEfloatgR = { "TMatrixTColumn_const<float>" , 99 , -1 };
G__linked_taginfo G__DmtpcDataConverterCintLN_TMatrixTFlat_constlEfloatgR = { "TMatrixTFlat_const<float>" , 99 , -1 };
G__linked_taginfo G__DmtpcDataConverterCintLN_TMatrixTSub_constlEfloatgR = { "TMatrixTSub_const<float>" , 99 , -1 };
G__linked_taginfo G__DmtpcDataConverterCintLN_TMatrixTSparseRow_constlEfloatgR = { "TMatrixTSparseRow_const<float>" , 99 , -1 };
G__linked_taginfo G__DmtpcDataConverterCintLN_TMatrixTSparseDiag_constlEfloatgR = { "TMatrixTSparseDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__DmtpcDataConverterCintLN_TMatrixTColumnlEfloatgR = { "TMatrixTColumn<float>" , 99 , -1 };
G__linked_taginfo G__DmtpcDataConverterCintLN_TMatrixTDiaglEfloatgR = { "TMatrixTDiag<float>" , 99 , -1 };
G__linked_taginfo G__DmtpcDataConverterCintLN_TMatrixTFlatlEfloatgR = { "TMatrixTFlat<float>" , 99 , -1 };
G__linked_taginfo G__DmtpcDataConverterCintLN_TMatrixTSublEfloatgR = { "TMatrixTSub<float>" , 99 , -1 };
G__linked_taginfo G__DmtpcDataConverterCintLN_TMatrixTSparseRowlEfloatgR = { "TMatrixTSparseRow<float>" , 99 , -1 };
G__linked_taginfo G__DmtpcDataConverterCintLN_TMatrixTSparseDiaglEfloatgR = { "TMatrixTSparseDiag<float>" , 99 , -1 };
G__linked_taginfo G__DmtpcDataConverterCintLN_DmtpcDataConverter = { "DmtpcDataConverter" , 110 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableDmtpcDataConverterCint() {
  G__DmtpcDataConverterCintLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR.tagnum = -1 ;
  G__DmtpcDataConverterCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__DmtpcDataConverterCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__DmtpcDataConverterCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__DmtpcDataConverterCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__DmtpcDataConverterCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__DmtpcDataConverterCintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR.tagnum = -1 ;
  G__DmtpcDataConverterCintLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__DmtpcDataConverterCintLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__DmtpcDataConverterCintLN_TH1F.tagnum = -1 ;
  G__DmtpcDataConverterCintLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__DmtpcDataConverterCintLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__DmtpcDataConverterCintLN_TH2S.tagnum = -1 ;
  G__DmtpcDataConverterCintLN_TH2F.tagnum = -1 ;
  G__DmtpcDataConverterCintLN_ScopeWaveformData.tagnum = -1 ;
  G__DmtpcDataConverterCintLN_vectorlESimpleConfigStore_tcOallocatorlESimpleConfigStore_tgRsPgR.tagnum = -1 ;
  G__DmtpcDataConverterCintLN_reverse_iteratorlEvectorlESimpleConfigStore_tcOallocatorlESimpleConfigStore_tgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__DmtpcDataConverterCintLN_vectorlETStringcOallocatorlETStringgRsPgR.tagnum = -1 ;
  G__DmtpcDataConverterCintLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__DmtpcDataConverterCintLN_ScopeDataInfo.tagnum = -1 ;
  G__DmtpcDataConverterCintLN_DmtpcEvent.tagnum = -1 ;
  G__DmtpcDataConverterCintLN_vectorlETH2FmUcOallocatorlETH2FmUgRsPgR.tagnum = -1 ;
  G__DmtpcDataConverterCintLN_reverse_iteratorlEvectorlETH2FmUcOallocatorlETH2FmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__DmtpcDataConverterCintLN_vectorlETH1FmUcOallocatorlETH1FmUgRsPgR.tagnum = -1 ;
  G__DmtpcDataConverterCintLN_reverse_iteratorlEvectorlETH1FmUcOallocatorlETH1FmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__DmtpcDataConverterCintLN_TElementActionTlEfloatgR.tagnum = -1 ;
  G__DmtpcDataConverterCintLN_TElementPosActionTlEfloatgR.tagnum = -1 ;
  G__DmtpcDataConverterCintLN_TMatrixTlEfloatgR.tagnum = -1 ;
  G__DmtpcDataConverterCintLN_TMatrixTRow_constlEfloatgR.tagnum = -1 ;
  G__DmtpcDataConverterCintLN_TMatrixTRowlEfloatgR.tagnum = -1 ;
  G__DmtpcDataConverterCintLN_TMatrixTDiag_constlEfloatgR.tagnum = -1 ;
  G__DmtpcDataConverterCintLN_TMatrixTColumn_constlEfloatgR.tagnum = -1 ;
  G__DmtpcDataConverterCintLN_TMatrixTFlat_constlEfloatgR.tagnum = -1 ;
  G__DmtpcDataConverterCintLN_TMatrixTSub_constlEfloatgR.tagnum = -1 ;
  G__DmtpcDataConverterCintLN_TMatrixTSparseRow_constlEfloatgR.tagnum = -1 ;
  G__DmtpcDataConverterCintLN_TMatrixTSparseDiag_constlEfloatgR.tagnum = -1 ;
  G__DmtpcDataConverterCintLN_TMatrixTColumnlEfloatgR.tagnum = -1 ;
  G__DmtpcDataConverterCintLN_TMatrixTDiaglEfloatgR.tagnum = -1 ;
  G__DmtpcDataConverterCintLN_TMatrixTFlatlEfloatgR.tagnum = -1 ;
  G__DmtpcDataConverterCintLN_TMatrixTSublEfloatgR.tagnum = -1 ;
  G__DmtpcDataConverterCintLN_TMatrixTSparseRowlEfloatgR.tagnum = -1 ;
  G__DmtpcDataConverterCintLN_TMatrixTSparseDiaglEfloatgR.tagnum = -1 ;
  G__DmtpcDataConverterCintLN_DmtpcDataConverter.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableDmtpcDataConverterCint() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__DmtpcDataConverterCintLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR);
   G__get_linked_tagnum_fwd(&G__DmtpcDataConverterCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__DmtpcDataConverterCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__DmtpcDataConverterCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__DmtpcDataConverterCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__DmtpcDataConverterCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__DmtpcDataConverterCintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__DmtpcDataConverterCintLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__DmtpcDataConverterCintLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__DmtpcDataConverterCintLN_TH1F);
   G__get_linked_tagnum_fwd(&G__DmtpcDataConverterCintLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__DmtpcDataConverterCintLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__DmtpcDataConverterCintLN_TH2S);
   G__get_linked_tagnum_fwd(&G__DmtpcDataConverterCintLN_TH2F);
   G__get_linked_tagnum_fwd(&G__DmtpcDataConverterCintLN_ScopeWaveformData);
   G__get_linked_tagnum_fwd(&G__DmtpcDataConverterCintLN_vectorlESimpleConfigStore_tcOallocatorlESimpleConfigStore_tgRsPgR);
   G__get_linked_tagnum_fwd(&G__DmtpcDataConverterCintLN_reverse_iteratorlEvectorlESimpleConfigStore_tcOallocatorlESimpleConfigStore_tgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__DmtpcDataConverterCintLN_vectorlETStringcOallocatorlETStringgRsPgR);
   G__get_linked_tagnum_fwd(&G__DmtpcDataConverterCintLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__DmtpcDataConverterCintLN_ScopeDataInfo);
   G__get_linked_tagnum_fwd(&G__DmtpcDataConverterCintLN_DmtpcEvent);
   G__get_linked_tagnum_fwd(&G__DmtpcDataConverterCintLN_vectorlETH2FmUcOallocatorlETH2FmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__DmtpcDataConverterCintLN_reverse_iteratorlEvectorlETH2FmUcOallocatorlETH2FmUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__DmtpcDataConverterCintLN_vectorlETH1FmUcOallocatorlETH1FmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__DmtpcDataConverterCintLN_reverse_iteratorlEvectorlETH1FmUcOallocatorlETH1FmUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__DmtpcDataConverterCintLN_TElementActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__DmtpcDataConverterCintLN_TElementPosActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__DmtpcDataConverterCintLN_TMatrixTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__DmtpcDataConverterCintLN_TMatrixTRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__DmtpcDataConverterCintLN_TMatrixTRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__DmtpcDataConverterCintLN_TMatrixTDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__DmtpcDataConverterCintLN_TMatrixTColumn_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__DmtpcDataConverterCintLN_TMatrixTFlat_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__DmtpcDataConverterCintLN_TMatrixTSub_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__DmtpcDataConverterCintLN_TMatrixTSparseRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__DmtpcDataConverterCintLN_TMatrixTSparseDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__DmtpcDataConverterCintLN_TMatrixTColumnlEfloatgR);
   G__get_linked_tagnum_fwd(&G__DmtpcDataConverterCintLN_TMatrixTDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__DmtpcDataConverterCintLN_TMatrixTFlatlEfloatgR);
   G__get_linked_tagnum_fwd(&G__DmtpcDataConverterCintLN_TMatrixTSublEfloatgR);
   G__get_linked_tagnum_fwd(&G__DmtpcDataConverterCintLN_TMatrixTSparseRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__DmtpcDataConverterCintLN_TMatrixTSparseDiaglEfloatgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__DmtpcDataConverterCintLN_DmtpcDataConverter),0,-1,0,(char*)NULL,G__setup_memvarDmtpcDataConverter,G__setup_memfuncDmtpcDataConverter);
}
extern "C" void G__cpp_setupDmtpcDataConverterCint(void) {
  G__check_setup_version(30051515,"G__cpp_setupDmtpcDataConverterCint()");
  G__set_cpp_environmentDmtpcDataConverterCint();
  G__cpp_setup_tagtableDmtpcDataConverterCint();

  G__cpp_setup_inheritanceDmtpcDataConverterCint();

  G__cpp_setup_typetableDmtpcDataConverterCint();

  G__cpp_setup_memvarDmtpcDataConverterCint();

  G__cpp_setup_memfuncDmtpcDataConverterCint();
  G__cpp_setup_globalDmtpcDataConverterCint();
  G__cpp_setup_funcDmtpcDataConverterCint();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncDmtpcDataConverterCint();
  return;
}
class G__cpp_setup_initDmtpcDataConverterCint {
  public:
    G__cpp_setup_initDmtpcDataConverterCint() { G__add_setup_func("DmtpcDataConverterCint",(G__incsetup)(&G__cpp_setupDmtpcDataConverterCint)); G__call_setup_funcs(); }
   ~G__cpp_setup_initDmtpcDataConverterCint() { G__remove_setup_func("DmtpcDataConverterCint"); }
};
G__cpp_setup_initDmtpcDataConverterCint G__cpp_setup_initializerDmtpcDataConverterCint;

