/********************************************************************
* DmtpcLocationCint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error DmtpcLocationCint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableDmtpcLocationCint();
extern void G__cpp_setup_inheritanceDmtpcLocationCint();
extern void G__cpp_setup_typetableDmtpcLocationCint();
extern void G__cpp_setup_memvarDmtpcLocationCint();
extern void G__cpp_setup_globalDmtpcLocationCint();
extern void G__cpp_setup_memfuncDmtpcLocationCint();
extern void G__cpp_setup_funcDmtpcLocationCint();
extern void G__set_cpp_environmentDmtpcLocationCint();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "DmtpcLocation.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__DmtpcLocationCintLN_TClass;
extern G__linked_taginfo G__DmtpcLocationCintLN_TBuffer;
extern G__linked_taginfo G__DmtpcLocationCintLN_TMemberInspector;
extern G__linked_taginfo G__DmtpcLocationCintLN_TObject;
extern G__linked_taginfo G__DmtpcLocationCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__DmtpcLocationCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DmtpcLocationCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__DmtpcLocationCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DmtpcLocationCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__DmtpcLocationCintLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__DmtpcLocationCintLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__DmtpcLocationCintLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__DmtpcLocationCintLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__DmtpcLocationCintLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__DmtpcLocationCintLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__DmtpcLocationCintLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__DmtpcLocationCintLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__DmtpcLocationCintLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__DmtpcLocationCintLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__DmtpcLocationCintLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__DmtpcLocationCintLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__DmtpcLocationCintLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__DmtpcLocationCintLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__DmtpcLocationCintLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__DmtpcLocationCintLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__DmtpcLocationCintLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__DmtpcLocationCintLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__DmtpcLocationCintLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__DmtpcLocationCintLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__DmtpcLocationCintLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__DmtpcLocationCintLN_TVector3;
extern G__linked_taginfo G__DmtpcLocationCintLN_DmtpcLocation;

/* STUB derived class for protected member access */
