//
// File generated by rootcint at Mon Jun  6 11:02:33 2016

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME DmtpcSRIMProjectionCint
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "DmtpcSRIMProjectionCint.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void DmtpcSRIMProjection_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void delete_DmtpcSRIMProjection(void *p);
   static void deleteArray_DmtpcSRIMProjection(void *p);
   static void destruct_DmtpcSRIMProjection(void *p);
   static void streamer_DmtpcSRIMProjection(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::DmtpcSRIMProjection*)
   {
      ::DmtpcSRIMProjection *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::DmtpcSRIMProjection >(0);
      static ::ROOT::TGenericClassInfo 
         instance("DmtpcSRIMProjection", ::DmtpcSRIMProjection::Class_Version(), "./DmtpcSRIMProjection.hh", 12,
                  typeid(::DmtpcSRIMProjection), DefineBehavior(ptr, ptr),
                  &::DmtpcSRIMProjection::Dictionary, isa_proxy, 0,
                  sizeof(::DmtpcSRIMProjection) );
      instance.SetDelete(&delete_DmtpcSRIMProjection);
      instance.SetDeleteArray(&deleteArray_DmtpcSRIMProjection);
      instance.SetDestructor(&destruct_DmtpcSRIMProjection);
      instance.SetStreamerFunc(&streamer_DmtpcSRIMProjection);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::DmtpcSRIMProjection*)
   {
      return GenerateInitInstanceLocal((::DmtpcSRIMProjection*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::DmtpcSRIMProjection*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *DmtpcSRIMProjection::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *DmtpcSRIMProjection::Class_Name()
{
   return "DmtpcSRIMProjection";
}

//______________________________________________________________________________
const char *DmtpcSRIMProjection::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::DmtpcSRIMProjection*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int DmtpcSRIMProjection::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::DmtpcSRIMProjection*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void DmtpcSRIMProjection::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::DmtpcSRIMProjection*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *DmtpcSRIMProjection::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::DmtpcSRIMProjection*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void DmtpcSRIMProjection::Streamer(TBuffer &R__b)
{
   // Stream an object of class DmtpcSRIMProjection.

   ::Error("DmtpcSRIMProjection::Streamer", "version id <=0 in ClassDef, dummy Streamer() called"); if (R__b.IsReading()) { }
}

//______________________________________________________________________________
void DmtpcSRIMProjection::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class DmtpcSRIMProjection.
      TClass *R__cl = ::DmtpcSRIMProjection::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*stoppingR", &stoppingR);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*srim_stoppingRSpline", &srim_stoppingRSpline);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "a", &a);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "b", &b);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "blur", &blur);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "gain", &gain);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "offset", &offset);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "lengthcal", &lengthcal);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "sin_theta", &sin_theta);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*func", &func);
}

namespace ROOT {
   // Wrapper around operator delete
   static void delete_DmtpcSRIMProjection(void *p) {
      delete ((::DmtpcSRIMProjection*)p);
   }
   static void deleteArray_DmtpcSRIMProjection(void *p) {
      delete [] ((::DmtpcSRIMProjection*)p);
   }
   static void destruct_DmtpcSRIMProjection(void *p) {
      typedef ::DmtpcSRIMProjection current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_DmtpcSRIMProjection(TBuffer &buf, void *obj) {
      ((::DmtpcSRIMProjection*)obj)->::DmtpcSRIMProjection::Streamer(buf);
   }
} // end of namespace ROOT for class ::DmtpcSRIMProjection

/********************************************************
* DmtpcSRIMProjectionCint.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableDmtpcSRIMProjectionCint();

extern "C" void G__set_cpp_environmentDmtpcSRIMProjectionCint() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("DmtpcSRIMProjection.hh");
  G__cpp_reset_tagtableDmtpcSRIMProjectionCint();
}
#include <new>
extern "C" int G__cpp_dllrevDmtpcSRIMProjectionCint() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* DmtpcSRIMProjection */
static int G__DmtpcSRIMProjectionCint_225_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   DmtpcSRIMProjection* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 5
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new DmtpcSRIMProjection(
(DmtpcSRIMProjection::PARTICLE) G__int(libp->para[0]), (double) G__double(libp->para[1])
, (double) G__double(libp->para[2]), (double) G__double(libp->para[3])
, (double) G__double(libp->para[4]));
   } else {
     p = new((void*) gvp) DmtpcSRIMProjection(
(DmtpcSRIMProjection::PARTICLE) G__int(libp->para[0]), (double) G__double(libp->para[1])
, (double) G__double(libp->para[2]), (double) G__double(libp->para[3])
, (double) G__double(libp->para[4]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__DmtpcSRIMProjectionCintLN_DmtpcSRIMProjection));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcSRIMProjectionCint_225_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   DmtpcSRIMProjection* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 5
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new DmtpcSRIMProjection(
(MaxCamSRIM*) G__int(libp->para[0]), (double) G__double(libp->para[1])
, (double) G__double(libp->para[2]), (double) G__double(libp->para[3])
, (double) G__double(libp->para[4]));
   } else {
     p = new((void*) gvp) DmtpcSRIMProjection(
(MaxCamSRIM*) G__int(libp->para[0]), (double) G__double(libp->para[1])
, (double) G__double(libp->para[2]), (double) G__double(libp->para[3])
, (double) G__double(libp->para[4]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__DmtpcSRIMProjectionCintLN_DmtpcSRIMProjection));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcSRIMProjectionCint_225_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      G__letdouble(result7, 100, (double) ((const DmtpcSRIMProjection*) G__getstructoffset())->dE((double) G__double(libp->para[0]), (double) G__double(libp->para[1])));
      break;
   case 1:
      G__letdouble(result7, 100, (double) ((const DmtpcSRIMProjection*) G__getstructoffset())->dE((double) G__double(libp->para[0])));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcSRIMProjectionCint_225_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((DmtpcSRIMProjection*) G__getstructoffset())->Eval((double*) G__int(libp->para[0]), (double*) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcSRIMProjectionCint_225_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 3:
      G__letdouble(result7, 100, (double) ((DmtpcSRIMProjection*) G__getstructoffset())->E((double) G__double(libp->para[0]), (double) G__double(libp->para[1])
, (double) G__double(libp->para[2])));
      break;
   case 2:
      G__letdouble(result7, 100, (double) ((DmtpcSRIMProjection*) G__getstructoffset())->E((double) G__double(libp->para[0]), (double) G__double(libp->para[1])));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcSRIMProjectionCint_225_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((DmtpcSRIMProjection*) G__getstructoffset())->setGain((double) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcSRIMProjectionCint_225_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((DmtpcSRIMProjection*) G__getstructoffset())->setSinTheta((double) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcSRIMProjectionCint_225_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((DmtpcSRIMProjection*) G__getstructoffset())->setOffset((double) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcSRIMProjectionCint_225_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((DmtpcSRIMProjection*) G__getstructoffset())->setLengthCal((double) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcSRIMProjectionCint_225_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      G__letint(result7, 85, (long) ((DmtpcSRIMProjection*) G__getstructoffset())->asFunction((const char*) G__int(libp->para[0]), (double) G__double(libp->para[1])));
      break;
   case 1:
      G__letint(result7, 85, (long) ((DmtpcSRIMProjection*) G__getstructoffset())->asFunction((const char*) G__int(libp->para[0])));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcSRIMProjectionCint_225_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((const DmtpcSRIMProjection*) G__getstructoffset())->spline());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcSRIMProjectionCint_225_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((const DmtpcSRIMProjection*) G__getstructoffset())->rawSpline());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcSRIMProjectionCint_225_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) DmtpcSRIMProjection::getFileName((DmtpcSRIMProjection::PARTICLE) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcSRIMProjectionCint_225_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) DmtpcSRIMProjection::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcSRIMProjectionCint_225_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) DmtpcSRIMProjection::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcSRIMProjectionCint_225_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) DmtpcSRIMProjection::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcSRIMProjectionCint_225_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      DmtpcSRIMProjection::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcSRIMProjectionCint_225_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((const DmtpcSRIMProjection*) G__getstructoffset())->IsA());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcSRIMProjectionCint_225_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((DmtpcSRIMProjection*) G__getstructoffset())->ShowMembers(*(TMemberInspector*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcSRIMProjectionCint_225_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((DmtpcSRIMProjection*) G__getstructoffset())->Streamer(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcSRIMProjectionCint_225_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((DmtpcSRIMProjection*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcSRIMProjectionCint_225_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) DmtpcSRIMProjection::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcSRIMProjectionCint_225_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) DmtpcSRIMProjection::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcSRIMProjectionCint_225_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) DmtpcSRIMProjection::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcSRIMProjectionCint_225_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) DmtpcSRIMProjection::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__DmtpcSRIMProjectionCint_225_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   DmtpcSRIMProjection* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new DmtpcSRIMProjection(*(DmtpcSRIMProjection*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__DmtpcSRIMProjectionCintLN_DmtpcSRIMProjection));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef DmtpcSRIMProjection G__TDmtpcSRIMProjection;
static int G__DmtpcSRIMProjectionCint_225_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (DmtpcSRIMProjection*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((DmtpcSRIMProjection*) (soff+(sizeof(DmtpcSRIMProjection)*i)))->~G__TDmtpcSRIMProjection();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (DmtpcSRIMProjection*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((DmtpcSRIMProjection*) (soff))->~G__TDmtpcSRIMProjection();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__DmtpcSRIMProjectionCint_225_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   DmtpcSRIMProjection* dest = (DmtpcSRIMProjection*) G__getstructoffset();
   *dest = *(DmtpcSRIMProjection*) libp->para[0].ref;
   const DmtpcSRIMProjection& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* DmtpcSRIMProjection */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncDmtpcSRIMProjectionCint {
 public:
  G__Sizep2memfuncDmtpcSRIMProjectionCint(): p(&G__Sizep2memfuncDmtpcSRIMProjectionCint::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncDmtpcSRIMProjectionCint::*p)();
};

size_t G__get_sizep2memfuncDmtpcSRIMProjectionCint()
{
  G__Sizep2memfuncDmtpcSRIMProjectionCint a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceDmtpcSRIMProjectionCint() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableDmtpcSRIMProjectionCint() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__DmtpcSRIMProjectionCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__DmtpcSRIMProjectionCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DmtpcSRIMProjectionCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__DmtpcSRIMProjectionCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DmtpcSRIMProjectionCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__DmtpcSRIMProjectionCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__DmtpcSRIMProjectionCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DmtpcSRIMProjectionCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__DmtpcSRIMProjectionCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DmtpcSRIMProjectionCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__DmtpcSRIMProjectionCintLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__DmtpcSRIMProjectionCintLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<double> >",117,G__get_linked_tagnum(&G__DmtpcSRIMProjectionCintLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__DmtpcSRIMProjectionCintLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DmtpcSRIMProjectionCintLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__DmtpcSRIMProjectionCintLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DmtpcSRIMProjectionCintLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<double,allocator<double> > >",117,G__get_linked_tagnum(&G__DmtpcSRIMProjectionCintLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__DmtpcSRIMProjectionCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__DmtpcSRIMProjectionCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__DmtpcSRIMProjectionCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__DmtpcSRIMProjectionCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* DmtpcSRIMProjection */
static void G__setup_memvarDmtpcSRIMProjection(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__DmtpcSRIMProjectionCintLN_DmtpcSRIMProjection));
   { DmtpcSRIMProjection *p; p=(DmtpcSRIMProjection*)0x1000; if (p) { }
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__DmtpcSRIMProjectionCintLN_DmtpcSRIMProjectioncLcLPARTICLE),-1,-2,1,G__FastAllocString(2048).Format("ALPHA=%lldLL",(long long)DmtpcSRIMProjection::ALPHA).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__DmtpcSRIMProjectionCintLN_DmtpcSRIMProjectioncLcLPARTICLE),-1,-2,1,G__FastAllocString(2048).Format("F=%lldLL",(long long)DmtpcSRIMProjection::F).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__DmtpcSRIMProjectionCintLN_DmtpcSRIMProjectioncLcLPARTICLE),-1,-2,1,G__FastAllocString(2048).Format("C=%lldLL",(long long)DmtpcSRIMProjection::C).data(),0,(char*)NULL);
   G__memvar_setup((void*)0,108,0,0,-1,-1,-1,4,"G__virtualinfo=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DmtpcSRIMProjectionCintLN_GausConvSpline),-1,-1,4,"stoppingR=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DmtpcSRIMProjectionCintLN_TSpline3),-1,-1,4,"srim_stoppingRSpline=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"a=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"b=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"blur=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"gain=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"offset=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"lengthcal=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"sin_theta=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DmtpcSRIMProjectionCintLN_TF1),-1,-1,4,"func=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DmtpcSRIMProjectionCintLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarDmtpcSRIMProjectionCint() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncDmtpcSRIMProjection(void) {
   /* DmtpcSRIMProjection */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__DmtpcSRIMProjectionCintLN_DmtpcSRIMProjection));
   G__memfunc_setup("DmtpcSRIMProjection",1872,G__DmtpcSRIMProjectionCint_225_0_1, 105, G__get_linked_tagnum(&G__DmtpcSRIMProjectionCintLN_DmtpcSRIMProjection), -1, 0, 5, 1, 1, 0, 
"i 'DmtpcSRIMProjection::PARTICLE' - 0 - type d - - 0 - blur_amt "
"d - - 0 - pressure d - - 0 - a "
"d - - 0 - b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DmtpcSRIMProjection",1872,G__DmtpcSRIMProjectionCint_225_0_2, 105, G__get_linked_tagnum(&G__DmtpcSRIMProjectionCintLN_DmtpcSRIMProjection), -1, 0, 5, 1, 1, 0, 
"U 'MaxCamSRIM' - 0 - srim d - - 0 - blur_amt "
"d - - 0 - pressure d - - 0 - a "
"d - - 0 - b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("dE",169,G__DmtpcSRIMProjectionCint_225_0_3, 100, -1, -1, 0, 2, 1, 1, 8, 
"d - - 0 - x d - - 0 '5' nsig", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Eval",392,G__DmtpcSRIMProjectionCint_225_0_4, 100, -1, -1, 0, 2, 1, 1, 0, 
"D - - 0 - x D - - 0 - p", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("E",69,G__DmtpcSRIMProjectionCint_225_0_5, 100, -1, -1, 0, 3, 1, 1, 0, 
"d - - 0 - x0 d - - 0 - x1 "
"d - - 0 '5' nsig", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setGain",715,G__DmtpcSRIMProjectionCint_225_0_6, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - adu_per_kev", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setSinTheta",1132,G__DmtpcSRIMProjectionCint_225_0_7, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - sin_theta", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setOffset",947,G__DmtpcSRIMProjectionCint_225_0_8, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - offset", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setLengthCal",1214,G__DmtpcSRIMProjectionCint_225_0_9, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - mm_per_px", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("asFunction",1050,G__DmtpcSRIMProjectionCint_225_0_10, 85, G__get_linked_tagnum(&G__DmtpcSRIMProjectionCintLN_TF1), -1, 0, 2, 1, 1, 0, 
"C - - 10 - name d - - 0 '5' nsig_bounds", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("spline",651,G__DmtpcSRIMProjectionCint_225_0_11, 85, G__get_linked_tagnum(&G__DmtpcSRIMProjectionCintLN_GausConvSpline), -1, 0, 0, 1, 1, 9, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("rawSpline",949,G__DmtpcSRIMProjectionCint_225_0_12, 85, G__get_linked_tagnum(&G__DmtpcSRIMProjectionCintLN_TSpline3), -1, 0, 0, 1, 1, 9, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getFileName",1089,G__DmtpcSRIMProjectionCint_225_0_13, 67, -1, -1, 0, 1, 3, 1, 1, "i 'DmtpcSRIMProjection::PARTICLE' - 0 - type", (char*)NULL, (void*) G__func2void( (const char* (*)(DmtpcSRIMProjection::PARTICLE))(&DmtpcSRIMProjection::getFileName) ), 0);
   G__memfunc_setup("Class",502,G__DmtpcSRIMProjectionCint_225_0_14, 85, G__get_linked_tagnum(&G__DmtpcSRIMProjectionCintLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&DmtpcSRIMProjection::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__DmtpcSRIMProjectionCint_225_0_15, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&DmtpcSRIMProjection::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__DmtpcSRIMProjectionCint_225_0_16, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&DmtpcSRIMProjection::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__DmtpcSRIMProjectionCint_225_0_17, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&DmtpcSRIMProjection::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,G__DmtpcSRIMProjectionCint_225_0_18, 85, G__get_linked_tagnum(&G__DmtpcSRIMProjectionCintLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,G__DmtpcSRIMProjectionCint_225_0_19, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - insp", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,G__DmtpcSRIMProjectionCint_225_0_20, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__DmtpcSRIMProjectionCint_225_0_21, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__DmtpcSRIMProjectionCint_225_0_22, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&DmtpcSRIMProjection::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__DmtpcSRIMProjectionCint_225_0_23, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&DmtpcSRIMProjection::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__DmtpcSRIMProjectionCint_225_0_24, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&DmtpcSRIMProjection::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__DmtpcSRIMProjectionCint_225_0_25, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&DmtpcSRIMProjection::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("DmtpcSRIMProjection", 1872, G__DmtpcSRIMProjectionCint_225_0_26, (int) ('i'), G__get_linked_tagnum(&G__DmtpcSRIMProjectionCintLN_DmtpcSRIMProjection), -1, 0, 1, 1, 1, 0, "u 'DmtpcSRIMProjection' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~DmtpcSRIMProjection", 1998, G__DmtpcSRIMProjectionCint_225_0_27, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__DmtpcSRIMProjectionCint_225_0_28, (int) ('u'), G__get_linked_tagnum(&G__DmtpcSRIMProjectionCintLN_DmtpcSRIMProjection), -1, 1, 1, 1, 1, 0, "u 'DmtpcSRIMProjection' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncDmtpcSRIMProjectionCint() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalDmtpcSRIMProjectionCint() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcDmtpcSRIMProjectionCint() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__DmtpcSRIMProjectionCintLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__DmtpcSRIMProjectionCintLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__DmtpcSRIMProjectionCintLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__DmtpcSRIMProjectionCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__DmtpcSRIMProjectionCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__DmtpcSRIMProjectionCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__DmtpcSRIMProjectionCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__DmtpcSRIMProjectionCintLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__DmtpcSRIMProjectionCintLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__DmtpcSRIMProjectionCintLN_TF1 = { "TF1" , 99 , -1 };
G__linked_taginfo G__DmtpcSRIMProjectionCintLN_TSpline3 = { "TSpline3" , 99 , -1 };
G__linked_taginfo G__DmtpcSRIMProjectionCintLN_GausConvSpline = { "GausConvSpline" , 99 , -1 };
G__linked_taginfo G__DmtpcSRIMProjectionCintLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR = { "vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > >" , 99 , -1 };
G__linked_taginfo G__DmtpcSRIMProjectionCintLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > >::iterator>" , 99 , -1 };
G__linked_taginfo G__DmtpcSRIMProjectionCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__DmtpcSRIMProjectionCintLN_MaxCamSRIM = { "MaxCamSRIM" , 99 , -1 };
G__linked_taginfo G__DmtpcSRIMProjectionCintLN_DmtpcSRIMProjection = { "DmtpcSRIMProjection" , 99 , -1 };
G__linked_taginfo G__DmtpcSRIMProjectionCintLN_DmtpcSRIMProjectioncLcLPARTICLE = { "DmtpcSRIMProjection::PARTICLE" , 101 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableDmtpcSRIMProjectionCint() {
  G__DmtpcSRIMProjectionCintLN_TClass.tagnum = -1 ;
  G__DmtpcSRIMProjectionCintLN_TBuffer.tagnum = -1 ;
  G__DmtpcSRIMProjectionCintLN_TMemberInspector.tagnum = -1 ;
  G__DmtpcSRIMProjectionCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__DmtpcSRIMProjectionCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__DmtpcSRIMProjectionCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__DmtpcSRIMProjectionCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__DmtpcSRIMProjectionCintLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__DmtpcSRIMProjectionCintLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__DmtpcSRIMProjectionCintLN_TF1.tagnum = -1 ;
  G__DmtpcSRIMProjectionCintLN_TSpline3.tagnum = -1 ;
  G__DmtpcSRIMProjectionCintLN_GausConvSpline.tagnum = -1 ;
  G__DmtpcSRIMProjectionCintLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR.tagnum = -1 ;
  G__DmtpcSRIMProjectionCintLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__DmtpcSRIMProjectionCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__DmtpcSRIMProjectionCintLN_MaxCamSRIM.tagnum = -1 ;
  G__DmtpcSRIMProjectionCintLN_DmtpcSRIMProjection.tagnum = -1 ;
  G__DmtpcSRIMProjectionCintLN_DmtpcSRIMProjectioncLcLPARTICLE.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableDmtpcSRIMProjectionCint() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__DmtpcSRIMProjectionCintLN_TClass);
   G__get_linked_tagnum_fwd(&G__DmtpcSRIMProjectionCintLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__DmtpcSRIMProjectionCintLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__DmtpcSRIMProjectionCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__DmtpcSRIMProjectionCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__DmtpcSRIMProjectionCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__DmtpcSRIMProjectionCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__DmtpcSRIMProjectionCintLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__DmtpcSRIMProjectionCintLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__DmtpcSRIMProjectionCintLN_TF1);
   G__get_linked_tagnum_fwd(&G__DmtpcSRIMProjectionCintLN_TSpline3);
   G__get_linked_tagnum_fwd(&G__DmtpcSRIMProjectionCintLN_GausConvSpline);
   G__get_linked_tagnum_fwd(&G__DmtpcSRIMProjectionCintLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__DmtpcSRIMProjectionCintLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__DmtpcSRIMProjectionCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__DmtpcSRIMProjectionCintLN_MaxCamSRIM);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__DmtpcSRIMProjectionCintLN_DmtpcSRIMProjection),sizeof(DmtpcSRIMProjection),-1,33792,(char*)NULL,G__setup_memvarDmtpcSRIMProjection,G__setup_memfuncDmtpcSRIMProjection);
   G__get_linked_tagnum_fwd(&G__DmtpcSRIMProjectionCintLN_DmtpcSRIMProjectioncLcLPARTICLE);
}
extern "C" void G__cpp_setupDmtpcSRIMProjectionCint(void) {
  G__check_setup_version(30051515,"G__cpp_setupDmtpcSRIMProjectionCint()");
  G__set_cpp_environmentDmtpcSRIMProjectionCint();
  G__cpp_setup_tagtableDmtpcSRIMProjectionCint();

  G__cpp_setup_inheritanceDmtpcSRIMProjectionCint();

  G__cpp_setup_typetableDmtpcSRIMProjectionCint();

  G__cpp_setup_memvarDmtpcSRIMProjectionCint();

  G__cpp_setup_memfuncDmtpcSRIMProjectionCint();
  G__cpp_setup_globalDmtpcSRIMProjectionCint();
  G__cpp_setup_funcDmtpcSRIMProjectionCint();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncDmtpcSRIMProjectionCint();
  return;
}
class G__cpp_setup_initDmtpcSRIMProjectionCint {
  public:
    G__cpp_setup_initDmtpcSRIMProjectionCint() { G__add_setup_func("DmtpcSRIMProjectionCint",(G__incsetup)(&G__cpp_setupDmtpcSRIMProjectionCint)); G__call_setup_funcs(); }
   ~G__cpp_setup_initDmtpcSRIMProjectionCint() { G__remove_setup_func("DmtpcSRIMProjectionCint"); }
};
G__cpp_setup_initDmtpcSRIMProjectionCint G__cpp_setup_initializerDmtpcSRIMProjectionCint;

