//
// File generated by rootcint at Tue Aug 16 18:39:34 2016

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME DmtpcDatasetCint
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "DmtpcDatasetCint.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void DmtpcDataset_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_DmtpcDataset(void *p = 0);
   static void *newArray_DmtpcDataset(Long_t size, void *p);
   static void delete_DmtpcDataset(void *p);
   static void deleteArray_DmtpcDataset(void *p);
   static void destruct_DmtpcDataset(void *p);
   static void streamer_DmtpcDataset(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::DmtpcDataset*)
   {
      ::DmtpcDataset *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::DmtpcDataset >(0);
      static ::ROOT::TGenericClassInfo 
         instance("DmtpcDataset", ::DmtpcDataset::Class_Version(), "./DmtpcDataset.hh", 25,
                  typeid(::DmtpcDataset), DefineBehavior(ptr, ptr),
                  &::DmtpcDataset::Dictionary, isa_proxy, 0,
                  sizeof(::DmtpcDataset) );
      instance.SetNew(&new_DmtpcDataset);
      instance.SetNewArray(&newArray_DmtpcDataset);
      instance.SetDelete(&delete_DmtpcDataset);
      instance.SetDeleteArray(&deleteArray_DmtpcDataset);
      instance.SetDestructor(&destruct_DmtpcDataset);
      instance.SetStreamerFunc(&streamer_DmtpcDataset);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::DmtpcDataset*)
   {
      return GenerateInitInstanceLocal((::DmtpcDataset*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::DmtpcDataset*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *DmtpcDataset::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *DmtpcDataset::Class_Name()
{
   return "DmtpcDataset";
}

//______________________________________________________________________________
const char *DmtpcDataset::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::DmtpcDataset*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int DmtpcDataset::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::DmtpcDataset*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void DmtpcDataset::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::DmtpcDataset*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *DmtpcDataset::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::DmtpcDataset*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void DmtpcDataset::Streamer(TBuffer &R__b)
{
   // Stream an object of class DmtpcDataset.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      TObject::Streamer(R__b);
      R__b >> _imageTree;
      R__b >> _file;
      R__b >> _event;
      R__b >> _comment;
      R__b >> _location;
      R__b >> _keyword;
      R__b >> _detId;
      _savedLocation.Streamer(R__b);
      _listOfDetectorParts->Streamer(R__b);
      R__b >> _inittime;
      R__b.CheckByteCount(R__s, R__c, DmtpcDataset::IsA());
   } else {
      R__c = R__b.WriteVersion(DmtpcDataset::IsA(), kTRUE);
      TObject::Streamer(R__b);
      R__b << _imageTree;
      R__b << _file;
      R__b << _event;
      R__b << _comment;
      R__b << _location;
      R__b << _keyword;
      R__b << _detId;
      _savedLocation.Streamer(R__b);
      _listOfDetectorParts->Streamer(R__b);
      R__b << _inittime;
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void DmtpcDataset::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class DmtpcDataset.
      TClass *R__cl = ::DmtpcDataset::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*_imageTree", &_imageTree);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*_file", &_file);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*_event", &_event);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*_comment", &_comment);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*_location", &_location);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*_keyword", &_keyword);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*_detId", &_detId);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "_savedLocation", &_savedLocation);
      R__insp.InspectMember(_savedLocation, "_savedLocation.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*_listOfDetectorParts", &_listOfDetectorParts);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*_inittime", &_inittime);
      TObject::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_DmtpcDataset(void *p) {
      return  p ? new(p) ::DmtpcDataset : new ::DmtpcDataset;
   }
   static void *newArray_DmtpcDataset(Long_t nElements, void *p) {
      return p ? new(p) ::DmtpcDataset[nElements] : new ::DmtpcDataset[nElements];
   }
   // Wrapper around operator delete
   static void delete_DmtpcDataset(void *p) {
      delete ((::DmtpcDataset*)p);
   }
   static void deleteArray_DmtpcDataset(void *p) {
      delete [] ((::DmtpcDataset*)p);
   }
   static void destruct_DmtpcDataset(void *p) {
      typedef ::DmtpcDataset current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_DmtpcDataset(TBuffer &buf, void *obj) {
      ((::DmtpcDataset*)obj)->::DmtpcDataset::Streamer(buf);
   }
} // end of namespace ROOT for class ::DmtpcDataset

/********************************************************
* DmtpcDatasetCint.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableDmtpcDatasetCint();

extern "C" void G__set_cpp_environmentDmtpcDatasetCint() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("DmtpcDataset.hh");
  G__cpp_reset_tagtableDmtpcDatasetCint();
}
#include <new>
extern "C" int G__cpp_dllrevDmtpcDatasetCint() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* DmtpcDataset */
static int G__DmtpcDatasetCint_683_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   DmtpcDataset* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new DmtpcDataset[n];
     } else {
       p = new((void*) gvp) DmtpcDataset[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new DmtpcDataset;
     } else {
       p = new((void*) gvp) DmtpcDataset;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__DmtpcDatasetCintLN_DmtpcDataset));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcDatasetCint_683_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   DmtpcDataset* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 1
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new DmtpcDataset(*(DmtpcDataset*) libp->para[0].ref);
   } else {
     p = new((void*) gvp) DmtpcDataset(*(DmtpcDataset*) libp->para[0].ref);
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__DmtpcDatasetCintLN_DmtpcDataset));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcDatasetCint_683_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((DmtpcDataset*) G__getstructoffset())->write();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcDatasetCint_683_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((DmtpcDataset*) G__getstructoffset())->tree());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcDatasetCint_683_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((DmtpcDataset*) G__getstructoffset())->chain());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcDatasetCint_683_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((DmtpcDataset*) G__getstructoffset())->file());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcDatasetCint_683_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((DmtpcDataset*) G__getstructoffset())->createRootFile((const char*) G__int(libp->para[0]), *((TString*) G__int(libp->para[1])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcDatasetCint_683_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((DmtpcDataset*) G__getstructoffset())->openRootFile((const char*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcDatasetCint_683_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((DmtpcDataset*) G__getstructoffset())->closeRootFile();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcDatasetCint_683_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((DmtpcDataset*) G__getstructoffset())->fill();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcDatasetCint_683_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((DmtpcDataset*) G__getstructoffset())->autoSave();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcDatasetCint_683_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) ((DmtpcDataset*) G__getstructoffset())->getFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcDatasetCint_683_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((DmtpcDataset*) G__getstructoffset())->clearEventMemory();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcDatasetCint_683_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((DmtpcDataset*) G__getstructoffset())->event());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcDatasetCint_683_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      G__letint(result7, 105, (long) ((DmtpcDataset*) G__getstructoffset())->saveRun((char*) G__int(libp->para[0]), (char*) G__int(libp->para[1])));
      break;
   case 1:
      G__letint(result7, 105, (long) ((DmtpcDataset*) G__getstructoffset())->saveRun((char*) G__int(libp->para[0])));
      break;
   case 0:
      G__letint(result7, 105, (long) ((DmtpcDataset*) G__getstructoffset())->saveRun());
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcDatasetCint_683_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((DmtpcDataset*) G__getstructoffset())->getEvent((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcDatasetCint_683_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((DmtpcDataset*) G__getstructoffset())->getBiasFrame((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcDatasetCint_683_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((DmtpcDataset*) G__getstructoffset())->getBiasFrameOverscan((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcDatasetCint_683_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((DmtpcDataset*) G__getstructoffset())->getNbiasFrames());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcDatasetCint_683_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((DmtpcDataset*) G__getstructoffset())->getNcameras());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcDatasetCint_683_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((DmtpcDataset*) G__getstructoffset())->darksub((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcDatasetCint_683_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((DmtpcDataset*) G__getstructoffset())->showimg((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcDatasetCint_683_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((DmtpcDataset*) G__getstructoffset())->setRunNumberFromDB((const char*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcDatasetCint_683_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((DmtpcDataset*) G__getstructoffset())->setComment(*((TString*) G__int(libp->para[0])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcDatasetCint_683_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((DmtpcDataset*) G__getstructoffset())->comment());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcDatasetCint_683_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((DmtpcDataset*) G__getstructoffset())->setKeyword(*((TString*) G__int(libp->para[0])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcDatasetCint_683_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((DmtpcDataset*) G__getstructoffset())->keyword());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcDatasetCint_683_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((DmtpcDataset*) G__getstructoffset())->setLocation(*((TString*) G__int(libp->para[0])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcDatasetCint_683_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((DmtpcDataset*) G__getstructoffset())->location());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcDatasetCint_683_0_31(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((DmtpcDataset*) G__getstructoffset())->setDetId(*((TString*) G__int(libp->para[0])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcDatasetCint_683_0_32(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((DmtpcDataset*) G__getstructoffset())->detId());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcDatasetCint_683_0_33(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((DmtpcDataset*) G__getstructoffset())->listOfDetectorParts());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcDatasetCint_683_0_34(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((DmtpcDataset*) G__getstructoffset())->getDetectorPart((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcDatasetCint_683_0_35(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         TString* pobj;
         TString xobj = ((DmtpcDataset*) G__getstructoffset())->getSavedLocation();
         pobj = new TString(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcDatasetCint_683_0_36(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) DmtpcDataset::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcDatasetCint_683_0_37(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) DmtpcDataset::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcDatasetCint_683_0_38(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) DmtpcDataset::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcDatasetCint_683_0_39(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      DmtpcDataset::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcDatasetCint_683_0_43(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((DmtpcDataset*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcDatasetCint_683_0_44(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) DmtpcDataset::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcDatasetCint_683_0_45(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) DmtpcDataset::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcDatasetCint_683_0_46(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) DmtpcDataset::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcDatasetCint_683_0_47(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) DmtpcDataset::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef DmtpcDataset G__TDmtpcDataset;
static int G__DmtpcDatasetCint_683_0_48(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (DmtpcDataset*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((DmtpcDataset*) (soff+(sizeof(DmtpcDataset)*i)))->~G__TDmtpcDataset();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (DmtpcDataset*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((DmtpcDataset*) (soff))->~G__TDmtpcDataset();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__DmtpcDatasetCint_683_0_49(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   DmtpcDataset* dest = (DmtpcDataset*) G__getstructoffset();
   *dest = *(DmtpcDataset*) libp->para[0].ref;
   const DmtpcDataset& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* DmtpcDataset */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncDmtpcDatasetCint {
 public:
  G__Sizep2memfuncDmtpcDatasetCint(): p(&G__Sizep2memfuncDmtpcDatasetCint::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncDmtpcDatasetCint::*p)();
};

size_t G__get_sizep2memfuncDmtpcDatasetCint()
{
  G__Sizep2memfuncDmtpcDatasetCint a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceDmtpcDatasetCint() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__DmtpcDatasetCintLN_DmtpcDataset))) {
     DmtpcDataset *G__Lderived;
     G__Lderived=(DmtpcDataset*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__DmtpcDatasetCintLN_DmtpcDataset),G__get_linked_tagnum(&G__DmtpcDatasetCintLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableDmtpcDatasetCint() {

   /* Setting up typedef entry */
   G__search_typename2("Int_t",105,-1,0,-1);
   G__setnewtype(-1,"Signed integer 4 bytes (int)",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__DmtpcDatasetCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__DmtpcDatasetCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DmtpcDatasetCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__DmtpcDatasetCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DmtpcDatasetCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__DmtpcDatasetCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__DmtpcDatasetCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DmtpcDatasetCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__DmtpcDatasetCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DmtpcDatasetCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__DmtpcDatasetCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__DmtpcDatasetCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__DmtpcDatasetCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__DmtpcDatasetCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TObjArray*>",117,G__get_linked_tagnum(&G__DmtpcDatasetCintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__DmtpcDatasetCintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*,less<string> >",117,G__get_linked_tagnum(&G__DmtpcDatasetCintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__DmtpcDatasetCintLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__DmtpcDatasetCintLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__DmtpcDatasetCintLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__DmtpcDatasetCintLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<SimpleConfigStore_t>",117,G__get_linked_tagnum(&G__DmtpcDatasetCintLN_vectorlESimpleConfigStore_tcOallocatorlESimpleConfigStore_tgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__DmtpcDatasetCintLN_reverse_iteratorlEvectorlESimpleConfigStore_tcOallocatorlESimpleConfigStore_tgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DmtpcDatasetCintLN_vectorlESimpleConfigStore_tcOallocatorlESimpleConfigStore_tgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__DmtpcDatasetCintLN_reverse_iteratorlEvectorlESimpleConfigStore_tcOallocatorlESimpleConfigStore_tgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DmtpcDatasetCintLN_vectorlESimpleConfigStore_tcOallocatorlESimpleConfigStore_tgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<UInt_t>",117,G__get_linked_tagnum(&G__DmtpcDatasetCintLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TString>",117,G__get_linked_tagnum(&G__DmtpcDatasetCintLN_vectorlETStringcOallocatorlETStringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__DmtpcDatasetCintLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DmtpcDatasetCintLN_vectorlETStringcOallocatorlETStringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__DmtpcDatasetCintLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DmtpcDatasetCintLN_vectorlETStringcOallocatorlETStringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TH2F*>",117,G__get_linked_tagnum(&G__DmtpcDatasetCintLN_vectorlETH2FmUcOallocatorlETH2FmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__DmtpcDatasetCintLN_reverse_iteratorlEvectorlETH2FmUcOallocatorlETH2FmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DmtpcDatasetCintLN_vectorlETH2FmUcOallocatorlETH2FmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__DmtpcDatasetCintLN_reverse_iteratorlEvectorlETH2FmUcOallocatorlETH2FmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DmtpcDatasetCintLN_vectorlETH2FmUcOallocatorlETH2FmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TH1F*>",117,G__get_linked_tagnum(&G__DmtpcDatasetCintLN_vectorlETH1FmUcOallocatorlETH1FmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__DmtpcDatasetCintLN_reverse_iteratorlEvectorlETH1FmUcOallocatorlETH1FmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DmtpcDatasetCintLN_vectorlETH1FmUcOallocatorlETH1FmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__DmtpcDatasetCintLN_reverse_iteratorlEvectorlETH1FmUcOallocatorlETH1FmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DmtpcDatasetCintLN_vectorlETH1FmUcOallocatorlETH1FmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixT<Float_t>",117,G__get_linked_tagnum(&G__DmtpcDatasetCintLN_TMatrixTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow_const<Float_t>",117,G__get_linked_tagnum(&G__DmtpcDatasetCintLN_TMatrixTRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn_const<Float_t>",117,G__get_linked_tagnum(&G__DmtpcDatasetCintLN_TMatrixTColumn_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag_const<Float_t>",117,G__get_linked_tagnum(&G__DmtpcDatasetCintLN_TMatrixTDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat_const<Float_t>",117,G__get_linked_tagnum(&G__DmtpcDatasetCintLN_TMatrixTFlat_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub_const<Float_t>",117,G__get_linked_tagnum(&G__DmtpcDatasetCintLN_TMatrixTSub_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow_const<Float_t>",117,G__get_linked_tagnum(&G__DmtpcDatasetCintLN_TMatrixTSparseRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag_const<Float_t>",117,G__get_linked_tagnum(&G__DmtpcDatasetCintLN_TMatrixTSparseDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow<Float_t>",117,G__get_linked_tagnum(&G__DmtpcDatasetCintLN_TMatrixTRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn<Float_t>",117,G__get_linked_tagnum(&G__DmtpcDatasetCintLN_TMatrixTColumnlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag<Float_t>",117,G__get_linked_tagnum(&G__DmtpcDatasetCintLN_TMatrixTDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat<Float_t>",117,G__get_linked_tagnum(&G__DmtpcDatasetCintLN_TMatrixTFlatlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub<Float_t>",117,G__get_linked_tagnum(&G__DmtpcDatasetCintLN_TMatrixTSublEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow<Float_t>",117,G__get_linked_tagnum(&G__DmtpcDatasetCintLN_TMatrixTSparseRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag<Float_t>",117,G__get_linked_tagnum(&G__DmtpcDatasetCintLN_TMatrixTSparseDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementActionT<Float_t>",117,G__get_linked_tagnum(&G__DmtpcDatasetCintLN_TElementActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementPosActionT<Float_t>",117,G__get_linked_tagnum(&G__DmtpcDatasetCintLN_TElementPosActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* DmtpcDataset */
static void G__setup_memvarDmtpcDataset(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__DmtpcDatasetCintLN_DmtpcDataset));
   { DmtpcDataset *p; p=(DmtpcDataset*)0x1000; if (p) { }
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DmtpcDatasetCintLN_TTree),-1,-1,4,"_imageTree=",0,"/< tree holding many events");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DmtpcDatasetCintLN_TFile),-1,-1,4,"_file=",0,"/< file containing the tree");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DmtpcDatasetCintLN_DmtpcEvent),-1,-1,4,"_event=",0,"/< Data from one event");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DmtpcDatasetCintLN_TObjString),-1,-1,4,"_comment=",0,"/< brief comment about run");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DmtpcDatasetCintLN_TObjString),-1,-1,4,"_location=",0,"/< run location");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DmtpcDatasetCintLN_TObjString),-1,-1,4,"_keyword=",0,"/< run keyword");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DmtpcDatasetCintLN_TObjString),-1,-1,4,"_detId=",0,"/< detector ID tag. used for setting file names ");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__DmtpcDatasetCintLN_TString),-1,-1,4,"_savedLocation=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DmtpcDatasetCintLN_TClonesArray),-1,-1,4,"_listOfDetectorParts=",0,"/< Array of detector parts");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DmtpcDatasetCintLN_TTimeStamp),-1,-1,4,"_inittime=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DmtpcDatasetCintLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarDmtpcDatasetCint() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncDmtpcDataset(void) {
   /* DmtpcDataset */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__DmtpcDatasetCintLN_DmtpcDataset));
   G__memfunc_setup("DmtpcDataset",1214,G__DmtpcDatasetCint_683_0_1, 105, G__get_linked_tagnum(&G__DmtpcDatasetCintLN_DmtpcDataset), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DmtpcDataset",1214,G__DmtpcDatasetCint_683_0_2, 105, G__get_linked_tagnum(&G__DmtpcDatasetCintLN_DmtpcDataset), -1, 0, 1, 1, 1, 0, "u 'DmtpcDataset' - 11 - other", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetName",673,(G__InterfaceMethod) NULL,67, -1, -1, 0, 0, 1, 1, 9, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("write",555,G__DmtpcDatasetCint_683_0_4, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("tree",432,G__DmtpcDatasetCint_683_0_5, 85, G__get_linked_tagnum(&G__DmtpcDatasetCintLN_TTree), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("chain",515,G__DmtpcDatasetCint_683_0_6, 85, G__get_linked_tagnum(&G__DmtpcDatasetCintLN_TChain), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("file",416,G__DmtpcDatasetCint_683_0_7, 85, G__get_linked_tagnum(&G__DmtpcDatasetCintLN_TFile), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("createRootFile",1432,G__DmtpcDatasetCint_683_0_8, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - fname u 'TString' - 0 - foption", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("openRootFile",1238,G__DmtpcDatasetCint_683_0_9, 121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - fname", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("closeRootFile",1338,G__DmtpcDatasetCint_683_0_10, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("fill",423,G__DmtpcDatasetCint_683_0_11, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("autoSave",840,G__DmtpcDatasetCint_683_0_12, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getFileName",1089,G__DmtpcDatasetCint_683_0_13, 67, -1, -1, 0, 0, 1, 1, 1, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("clearEventMemory",1666,G__DmtpcDatasetCint_683_0_14, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("event",546,G__DmtpcDatasetCint_683_0_15, 85, G__get_linked_tagnum(&G__DmtpcDatasetCintLN_DmtpcEvent), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("saveRun",740,G__DmtpcDatasetCint_683_0_16, 105, -1, -1, 0, 2, 1, 1, 0, 
"C - - 0 '\"mitdm10.mit.edu:/data/\"' scpdest C - - 0 '\"dbaccess.txt\"' fname", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getEvent",834,G__DmtpcDatasetCint_683_0_17, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getBiasFrame",1194,G__DmtpcDatasetCint_683_0_18, 85, G__get_linked_tagnum(&G__DmtpcDatasetCintLN_TH2F), -1, 0, 1, 1, 1, 0, "i - - 0 - iccd", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getBiasFrameOverscan",2027,G__DmtpcDatasetCint_683_0_19, 85, G__get_linked_tagnum(&G__DmtpcDatasetCintLN_TH2F), -1, 0, 1, 1, 1, 0, "i - - 0 - iccd", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getNbiasFrames",1419,G__DmtpcDatasetCint_683_0_20, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getNcameras",1130,G__DmtpcDatasetCint_683_0_21, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("darksub",748,G__DmtpcDatasetCint_683_0_22, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - iccd", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("showimg",766,G__DmtpcDatasetCint_683_0_23, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - iccd", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setRunNumberFromDB",1796,G__DmtpcDatasetCint_683_0_24, 105, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - dbAccessFile", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setComment",1055,G__DmtpcDatasetCint_683_0_25, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TString' - 0 - c", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("comment",755,G__DmtpcDatasetCint_683_0_26, 85, G__get_linked_tagnum(&G__DmtpcDatasetCintLN_TObjString), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setKeyword",1073,G__DmtpcDatasetCint_683_0_27, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TString' - 0 - c", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("keyword",773,G__DmtpcDatasetCint_683_0_28, 85, G__get_linked_tagnum(&G__DmtpcDatasetCintLN_TObjString), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setLocation",1157,G__DmtpcDatasetCint_683_0_29, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TString' - 0 - c", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("location",857,G__DmtpcDatasetCint_683_0_30, 85, G__get_linked_tagnum(&G__DmtpcDatasetCintLN_TObjString), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setDetId",790,G__DmtpcDatasetCint_683_0_31, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TString' - 0 - c", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("detId",490,G__DmtpcDatasetCint_683_0_32, 85, G__get_linked_tagnum(&G__DmtpcDatasetCintLN_TObjString), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("listOfDetectorParts",1973,G__DmtpcDatasetCint_683_0_33, 85, G__get_linked_tagnum(&G__DmtpcDatasetCintLN_TClonesArray), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getDetectorPart",1553,G__DmtpcDatasetCint_683_0_34, 85, G__get_linked_tagnum(&G__DmtpcDatasetCintLN_DmtpcDetectorPart), -1, 0, 1, 1, 1, 0, "i - - 0 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getSavedLocation",1644,G__DmtpcDatasetCint_683_0_35, 117, G__get_linked_tagnum(&G__DmtpcDatasetCintLN_TString), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__DmtpcDatasetCint_683_0_36, 85, G__get_linked_tagnum(&G__DmtpcDatasetCintLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&DmtpcDataset::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__DmtpcDatasetCint_683_0_37, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&DmtpcDataset::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__DmtpcDatasetCint_683_0_38, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&DmtpcDataset::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__DmtpcDatasetCint_683_0_39, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&DmtpcDataset::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__DmtpcDatasetCintLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - insp", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__DmtpcDatasetCint_683_0_43, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__DmtpcDatasetCint_683_0_44, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&DmtpcDataset::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__DmtpcDatasetCint_683_0_45, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&DmtpcDataset::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__DmtpcDatasetCint_683_0_46, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&DmtpcDataset::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__DmtpcDatasetCint_683_0_47, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&DmtpcDataset::DeclFileLine) ), 0);
   // automatic destructor
   G__memfunc_setup("~DmtpcDataset", 1340, G__DmtpcDatasetCint_683_0_48, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__DmtpcDatasetCint_683_0_49, (int) ('u'), G__get_linked_tagnum(&G__DmtpcDatasetCintLN_DmtpcDataset), -1, 1, 1, 1, 1, 0, "u 'DmtpcDataset' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncDmtpcDatasetCint() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {
}

static void G__cpp_setup_global5() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalDmtpcDatasetCint() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
  G__cpp_setup_global5();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcDmtpcDatasetCint() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__DmtpcDatasetCintLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__DmtpcDatasetCintLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__DmtpcDatasetCintLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__DmtpcDatasetCintLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__DmtpcDatasetCintLN_TString = { "TString" , 99 , -1 };
G__linked_taginfo G__DmtpcDatasetCintLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR = { "vector<unsigned int,allocator<unsigned int> >" , 99 , -1 };
G__linked_taginfo G__DmtpcDatasetCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__DmtpcDatasetCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__DmtpcDatasetCintLN_TClonesArray = { "TClonesArray" , 99 , -1 };
G__linked_taginfo G__DmtpcDatasetCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__DmtpcDatasetCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__DmtpcDatasetCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__DmtpcDatasetCintLN_TFile = { "TFile" , 99 , -1 };
G__linked_taginfo G__DmtpcDatasetCintLN_TTree = { "TTree" , 99 , -1 };
G__linked_taginfo G__DmtpcDatasetCintLN_TObjString = { "TObjString" , 99 , -1 };
G__linked_taginfo G__DmtpcDatasetCintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR = { "map<string,TObjArray*,less<string>,allocator<pair<const string,TObjArray*> > >" , 99 , -1 };
G__linked_taginfo G__DmtpcDatasetCintLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__DmtpcDatasetCintLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__DmtpcDatasetCintLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__DmtpcDatasetCintLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__DmtpcDatasetCintLN_TH2F = { "TH2F" , 99 , -1 };
G__linked_taginfo G__DmtpcDatasetCintLN_TTimeStamp = { "TTimeStamp" , 99 , -1 };
G__linked_taginfo G__DmtpcDatasetCintLN_TChain = { "TChain" , 99 , -1 };
G__linked_taginfo G__DmtpcDatasetCintLN_vectorlESimpleConfigStore_tcOallocatorlESimpleConfigStore_tgRsPgR = { "vector<SimpleConfigStore_t,allocator<SimpleConfigStore_t> >" , 99 , -1 };
G__linked_taginfo G__DmtpcDatasetCintLN_reverse_iteratorlEvectorlESimpleConfigStore_tcOallocatorlESimpleConfigStore_tgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<SimpleConfigStore_t,allocator<SimpleConfigStore_t> >::iterator>" , 99 , -1 };
G__linked_taginfo G__DmtpcDatasetCintLN_vectorlETStringcOallocatorlETStringgRsPgR = { "vector<TString,allocator<TString> >" , 99 , -1 };
G__linked_taginfo G__DmtpcDatasetCintLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TString,allocator<TString> >::iterator>" , 99 , -1 };
G__linked_taginfo G__DmtpcDatasetCintLN_DmtpcEvent = { "DmtpcEvent" , 99 , -1 };
G__linked_taginfo G__DmtpcDatasetCintLN_vectorlETH2FmUcOallocatorlETH2FmUgRsPgR = { "vector<TH2F*,allocator<TH2F*> >" , 99 , -1 };
G__linked_taginfo G__DmtpcDatasetCintLN_reverse_iteratorlEvectorlETH2FmUcOallocatorlETH2FmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TH2F*,allocator<TH2F*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__DmtpcDatasetCintLN_vectorlETH1FmUcOallocatorlETH1FmUgRsPgR = { "vector<TH1F*,allocator<TH1F*> >" , 99 , -1 };
G__linked_taginfo G__DmtpcDatasetCintLN_reverse_iteratorlEvectorlETH1FmUcOallocatorlETH1FmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TH1F*,allocator<TH1F*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__DmtpcDatasetCintLN_TElementActionTlEfloatgR = { "TElementActionT<float>" , 99 , -1 };
G__linked_taginfo G__DmtpcDatasetCintLN_TElementPosActionTlEfloatgR = { "TElementPosActionT<float>" , 99 , -1 };
G__linked_taginfo G__DmtpcDatasetCintLN_TMatrixTlEfloatgR = { "TMatrixT<float>" , 99 , -1 };
G__linked_taginfo G__DmtpcDatasetCintLN_TMatrixTRow_constlEfloatgR = { "TMatrixTRow_const<float>" , 99 , -1 };
G__linked_taginfo G__DmtpcDatasetCintLN_TMatrixTRowlEfloatgR = { "TMatrixTRow<float>" , 99 , -1 };
G__linked_taginfo G__DmtpcDatasetCintLN_TMatrixTDiag_constlEfloatgR = { "TMatrixTDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__DmtpcDatasetCintLN_TMatrixTColumn_constlEfloatgR = { "TMatrixTColumn_const<float>" , 99 , -1 };
G__linked_taginfo G__DmtpcDatasetCintLN_TMatrixTFlat_constlEfloatgR = { "TMatrixTFlat_const<float>" , 99 , -1 };
G__linked_taginfo G__DmtpcDatasetCintLN_TMatrixTSub_constlEfloatgR = { "TMatrixTSub_const<float>" , 99 , -1 };
G__linked_taginfo G__DmtpcDatasetCintLN_TMatrixTSparseRow_constlEfloatgR = { "TMatrixTSparseRow_const<float>" , 99 , -1 };
G__linked_taginfo G__DmtpcDatasetCintLN_TMatrixTSparseDiag_constlEfloatgR = { "TMatrixTSparseDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__DmtpcDatasetCintLN_TMatrixTColumnlEfloatgR = { "TMatrixTColumn<float>" , 99 , -1 };
G__linked_taginfo G__DmtpcDatasetCintLN_TMatrixTDiaglEfloatgR = { "TMatrixTDiag<float>" , 99 , -1 };
G__linked_taginfo G__DmtpcDatasetCintLN_TMatrixTFlatlEfloatgR = { "TMatrixTFlat<float>" , 99 , -1 };
G__linked_taginfo G__DmtpcDatasetCintLN_TMatrixTSublEfloatgR = { "TMatrixTSub<float>" , 99 , -1 };
G__linked_taginfo G__DmtpcDatasetCintLN_TMatrixTSparseRowlEfloatgR = { "TMatrixTSparseRow<float>" , 99 , -1 };
G__linked_taginfo G__DmtpcDatasetCintLN_TMatrixTSparseDiaglEfloatgR = { "TMatrixTSparseDiag<float>" , 99 , -1 };
G__linked_taginfo G__DmtpcDatasetCintLN_DmtpcDetectorPart = { "DmtpcDetectorPart" , 99 , -1 };
G__linked_taginfo G__DmtpcDatasetCintLN_DmtpcDataset = { "DmtpcDataset" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableDmtpcDatasetCint() {
  G__DmtpcDatasetCintLN_TClass.tagnum = -1 ;
  G__DmtpcDatasetCintLN_TBuffer.tagnum = -1 ;
  G__DmtpcDatasetCintLN_TMemberInspector.tagnum = -1 ;
  G__DmtpcDatasetCintLN_TObject.tagnum = -1 ;
  G__DmtpcDatasetCintLN_TString.tagnum = -1 ;
  G__DmtpcDatasetCintLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR.tagnum = -1 ;
  G__DmtpcDatasetCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__DmtpcDatasetCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__DmtpcDatasetCintLN_TClonesArray.tagnum = -1 ;
  G__DmtpcDatasetCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__DmtpcDatasetCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__DmtpcDatasetCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__DmtpcDatasetCintLN_TFile.tagnum = -1 ;
  G__DmtpcDatasetCintLN_TTree.tagnum = -1 ;
  G__DmtpcDatasetCintLN_TObjString.tagnum = -1 ;
  G__DmtpcDatasetCintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR.tagnum = -1 ;
  G__DmtpcDatasetCintLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__DmtpcDatasetCintLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__DmtpcDatasetCintLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__DmtpcDatasetCintLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__DmtpcDatasetCintLN_TH2F.tagnum = -1 ;
  G__DmtpcDatasetCintLN_TTimeStamp.tagnum = -1 ;
  G__DmtpcDatasetCintLN_TChain.tagnum = -1 ;
  G__DmtpcDatasetCintLN_vectorlESimpleConfigStore_tcOallocatorlESimpleConfigStore_tgRsPgR.tagnum = -1 ;
  G__DmtpcDatasetCintLN_reverse_iteratorlEvectorlESimpleConfigStore_tcOallocatorlESimpleConfigStore_tgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__DmtpcDatasetCintLN_vectorlETStringcOallocatorlETStringgRsPgR.tagnum = -1 ;
  G__DmtpcDatasetCintLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__DmtpcDatasetCintLN_DmtpcEvent.tagnum = -1 ;
  G__DmtpcDatasetCintLN_vectorlETH2FmUcOallocatorlETH2FmUgRsPgR.tagnum = -1 ;
  G__DmtpcDatasetCintLN_reverse_iteratorlEvectorlETH2FmUcOallocatorlETH2FmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__DmtpcDatasetCintLN_vectorlETH1FmUcOallocatorlETH1FmUgRsPgR.tagnum = -1 ;
  G__DmtpcDatasetCintLN_reverse_iteratorlEvectorlETH1FmUcOallocatorlETH1FmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__DmtpcDatasetCintLN_TElementActionTlEfloatgR.tagnum = -1 ;
  G__DmtpcDatasetCintLN_TElementPosActionTlEfloatgR.tagnum = -1 ;
  G__DmtpcDatasetCintLN_TMatrixTlEfloatgR.tagnum = -1 ;
  G__DmtpcDatasetCintLN_TMatrixTRow_constlEfloatgR.tagnum = -1 ;
  G__DmtpcDatasetCintLN_TMatrixTRowlEfloatgR.tagnum = -1 ;
  G__DmtpcDatasetCintLN_TMatrixTDiag_constlEfloatgR.tagnum = -1 ;
  G__DmtpcDatasetCintLN_TMatrixTColumn_constlEfloatgR.tagnum = -1 ;
  G__DmtpcDatasetCintLN_TMatrixTFlat_constlEfloatgR.tagnum = -1 ;
  G__DmtpcDatasetCintLN_TMatrixTSub_constlEfloatgR.tagnum = -1 ;
  G__DmtpcDatasetCintLN_TMatrixTSparseRow_constlEfloatgR.tagnum = -1 ;
  G__DmtpcDatasetCintLN_TMatrixTSparseDiag_constlEfloatgR.tagnum = -1 ;
  G__DmtpcDatasetCintLN_TMatrixTColumnlEfloatgR.tagnum = -1 ;
  G__DmtpcDatasetCintLN_TMatrixTDiaglEfloatgR.tagnum = -1 ;
  G__DmtpcDatasetCintLN_TMatrixTFlatlEfloatgR.tagnum = -1 ;
  G__DmtpcDatasetCintLN_TMatrixTSublEfloatgR.tagnum = -1 ;
  G__DmtpcDatasetCintLN_TMatrixTSparseRowlEfloatgR.tagnum = -1 ;
  G__DmtpcDatasetCintLN_TMatrixTSparseDiaglEfloatgR.tagnum = -1 ;
  G__DmtpcDatasetCintLN_DmtpcDetectorPart.tagnum = -1 ;
  G__DmtpcDatasetCintLN_DmtpcDataset.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableDmtpcDatasetCint() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__DmtpcDatasetCintLN_TClass);
   G__get_linked_tagnum_fwd(&G__DmtpcDatasetCintLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__DmtpcDatasetCintLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__DmtpcDatasetCintLN_TObject);
   G__get_linked_tagnum_fwd(&G__DmtpcDatasetCintLN_TString);
   G__get_linked_tagnum_fwd(&G__DmtpcDatasetCintLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR);
   G__get_linked_tagnum_fwd(&G__DmtpcDatasetCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__DmtpcDatasetCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__DmtpcDatasetCintLN_TClonesArray);
   G__get_linked_tagnum_fwd(&G__DmtpcDatasetCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__DmtpcDatasetCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__DmtpcDatasetCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__DmtpcDatasetCintLN_TFile);
   G__get_linked_tagnum_fwd(&G__DmtpcDatasetCintLN_TTree);
   G__get_linked_tagnum_fwd(&G__DmtpcDatasetCintLN_TObjString);
   G__get_linked_tagnum_fwd(&G__DmtpcDatasetCintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__DmtpcDatasetCintLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__DmtpcDatasetCintLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__DmtpcDatasetCintLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__DmtpcDatasetCintLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__DmtpcDatasetCintLN_TH2F);
   G__get_linked_tagnum_fwd(&G__DmtpcDatasetCintLN_TTimeStamp);
   G__get_linked_tagnum_fwd(&G__DmtpcDatasetCintLN_TChain);
   G__get_linked_tagnum_fwd(&G__DmtpcDatasetCintLN_vectorlESimpleConfigStore_tcOallocatorlESimpleConfigStore_tgRsPgR);
   G__get_linked_tagnum_fwd(&G__DmtpcDatasetCintLN_reverse_iteratorlEvectorlESimpleConfigStore_tcOallocatorlESimpleConfigStore_tgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__DmtpcDatasetCintLN_vectorlETStringcOallocatorlETStringgRsPgR);
   G__get_linked_tagnum_fwd(&G__DmtpcDatasetCintLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__DmtpcDatasetCintLN_DmtpcEvent);
   G__get_linked_tagnum_fwd(&G__DmtpcDatasetCintLN_vectorlETH2FmUcOallocatorlETH2FmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__DmtpcDatasetCintLN_reverse_iteratorlEvectorlETH2FmUcOallocatorlETH2FmUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__DmtpcDatasetCintLN_vectorlETH1FmUcOallocatorlETH1FmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__DmtpcDatasetCintLN_reverse_iteratorlEvectorlETH1FmUcOallocatorlETH1FmUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__DmtpcDatasetCintLN_TElementActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__DmtpcDatasetCintLN_TElementPosActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__DmtpcDatasetCintLN_TMatrixTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__DmtpcDatasetCintLN_TMatrixTRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__DmtpcDatasetCintLN_TMatrixTRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__DmtpcDatasetCintLN_TMatrixTDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__DmtpcDatasetCintLN_TMatrixTColumn_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__DmtpcDatasetCintLN_TMatrixTFlat_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__DmtpcDatasetCintLN_TMatrixTSub_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__DmtpcDatasetCintLN_TMatrixTSparseRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__DmtpcDatasetCintLN_TMatrixTSparseDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__DmtpcDatasetCintLN_TMatrixTColumnlEfloatgR);
   G__get_linked_tagnum_fwd(&G__DmtpcDatasetCintLN_TMatrixTDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__DmtpcDatasetCintLN_TMatrixTFlatlEfloatgR);
   G__get_linked_tagnum_fwd(&G__DmtpcDatasetCintLN_TMatrixTSublEfloatgR);
   G__get_linked_tagnum_fwd(&G__DmtpcDatasetCintLN_TMatrixTSparseRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__DmtpcDatasetCintLN_TMatrixTSparseDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__DmtpcDatasetCintLN_DmtpcDetectorPart);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__DmtpcDatasetCintLN_DmtpcDataset),sizeof(DmtpcDataset),-1,30464,(char*)NULL,G__setup_memvarDmtpcDataset,G__setup_memfuncDmtpcDataset);
}
extern "C" void G__cpp_setupDmtpcDatasetCint(void) {
  G__check_setup_version(30051515,"G__cpp_setupDmtpcDatasetCint()");
  G__set_cpp_environmentDmtpcDatasetCint();
  G__cpp_setup_tagtableDmtpcDatasetCint();

  G__cpp_setup_inheritanceDmtpcDatasetCint();

  G__cpp_setup_typetableDmtpcDatasetCint();

  G__cpp_setup_memvarDmtpcDatasetCint();

  G__cpp_setup_memfuncDmtpcDatasetCint();
  G__cpp_setup_globalDmtpcDatasetCint();
  G__cpp_setup_funcDmtpcDatasetCint();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncDmtpcDatasetCint();
  return;
}
class G__cpp_setup_initDmtpcDatasetCint {
  public:
    G__cpp_setup_initDmtpcDatasetCint() { G__add_setup_func("DmtpcDatasetCint",(G__incsetup)(&G__cpp_setupDmtpcDatasetCint)); G__call_setup_funcs(); }
   ~G__cpp_setup_initDmtpcDatasetCint() { G__remove_setup_func("DmtpcDatasetCint"); }
};
G__cpp_setup_initDmtpcDatasetCint G__cpp_setup_initializerDmtpcDatasetCint;

