/********************************************************************
* DmtpcSRIMProjectionCint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error DmtpcSRIMProjectionCint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableDmtpcSRIMProjectionCint();
extern void G__cpp_setup_inheritanceDmtpcSRIMProjectionCint();
extern void G__cpp_setup_typetableDmtpcSRIMProjectionCint();
extern void G__cpp_setup_memvarDmtpcSRIMProjectionCint();
extern void G__cpp_setup_globalDmtpcSRIMProjectionCint();
extern void G__cpp_setup_memfuncDmtpcSRIMProjectionCint();
extern void G__cpp_setup_funcDmtpcSRIMProjectionCint();
extern void G__set_cpp_environmentDmtpcSRIMProjectionCint();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "DmtpcSRIMProjection.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__DmtpcSRIMProjectionCintLN_TClass;
extern G__linked_taginfo G__DmtpcSRIMProjectionCintLN_TBuffer;
extern G__linked_taginfo G__DmtpcSRIMProjectionCintLN_TMemberInspector;
extern G__linked_taginfo G__DmtpcSRIMProjectionCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__DmtpcSRIMProjectionCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DmtpcSRIMProjectionCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__DmtpcSRIMProjectionCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DmtpcSRIMProjectionCintLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__DmtpcSRIMProjectionCintLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__DmtpcSRIMProjectionCintLN_TF1;
extern G__linked_taginfo G__DmtpcSRIMProjectionCintLN_TSpline3;
extern G__linked_taginfo G__DmtpcSRIMProjectionCintLN_GausConvSpline;
extern G__linked_taginfo G__DmtpcSRIMProjectionCintLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR;
extern G__linked_taginfo G__DmtpcSRIMProjectionCintLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DmtpcSRIMProjectionCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__DmtpcSRIMProjectionCintLN_MaxCamSRIM;
extern G__linked_taginfo G__DmtpcSRIMProjectionCintLN_DmtpcSRIMProjection;
extern G__linked_taginfo G__DmtpcSRIMProjectionCintLN_DmtpcSRIMProjectioncLcLPARTICLE;

/* STUB derived class for protected member access */
