/********************************************************************
* DmtpcEventTableEntryCint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error DmtpcEventTableEntryCint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableDmtpcEventTableEntryCint();
extern void G__cpp_setup_inheritanceDmtpcEventTableEntryCint();
extern void G__cpp_setup_typetableDmtpcEventTableEntryCint();
extern void G__cpp_setup_memvarDmtpcEventTableEntryCint();
extern void G__cpp_setup_globalDmtpcEventTableEntryCint();
extern void G__cpp_setup_memfuncDmtpcEventTableEntryCint();
extern void G__cpp_setup_funcDmtpcEventTableEntryCint();
extern void G__set_cpp_environmentDmtpcEventTableEntryCint();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "DmtpcEventTableEntry.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__DmtpcEventTableEntryCintLN_TClass;
extern G__linked_taginfo G__DmtpcEventTableEntryCintLN_TBuffer;
extern G__linked_taginfo G__DmtpcEventTableEntryCintLN_TMemberInspector;
extern G__linked_taginfo G__DmtpcEventTableEntryCintLN_TObject;
extern G__linked_taginfo G__DmtpcEventTableEntryCintLN_TString;
extern G__linked_taginfo G__DmtpcEventTableEntryCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__DmtpcEventTableEntryCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DmtpcEventTableEntryCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__DmtpcEventTableEntryCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DmtpcEventTableEntryCintLN_DmtpcEventTableEntry;

/* STUB derived class for protected member access */
