//
// File generated by rootcint at Tue Jul 12 17:20:15 2016

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME DmtpcDetectorPartCint
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "DmtpcDetectorPartCint.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void DmtpcDetectorPart_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_DmtpcDetectorPart(void *p = 0);
   static void *newArray_DmtpcDetectorPart(Long_t size, void *p);
   static void delete_DmtpcDetectorPart(void *p);
   static void deleteArray_DmtpcDetectorPart(void *p);
   static void destruct_DmtpcDetectorPart(void *p);
   static void streamer_DmtpcDetectorPart(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::DmtpcDetectorPart*)
   {
      ::DmtpcDetectorPart *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::DmtpcDetectorPart >(0);
      static ::ROOT::TGenericClassInfo 
         instance("DmtpcDetectorPart", ::DmtpcDetectorPart::Class_Version(), "./DmtpcDetectorPart.hh", 11,
                  typeid(::DmtpcDetectorPart), DefineBehavior(ptr, ptr),
                  &::DmtpcDetectorPart::Dictionary, isa_proxy, 0,
                  sizeof(::DmtpcDetectorPart) );
      instance.SetNew(&new_DmtpcDetectorPart);
      instance.SetNewArray(&newArray_DmtpcDetectorPart);
      instance.SetDelete(&delete_DmtpcDetectorPart);
      instance.SetDeleteArray(&deleteArray_DmtpcDetectorPart);
      instance.SetDestructor(&destruct_DmtpcDetectorPart);
      instance.SetStreamerFunc(&streamer_DmtpcDetectorPart);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::DmtpcDetectorPart*)
   {
      return GenerateInitInstanceLocal((::DmtpcDetectorPart*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::DmtpcDetectorPart*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *DmtpcDetectorPart::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *DmtpcDetectorPart::Class_Name()
{
   return "DmtpcDetectorPart";
}

//______________________________________________________________________________
const char *DmtpcDetectorPart::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::DmtpcDetectorPart*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int DmtpcDetectorPart::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::DmtpcDetectorPart*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void DmtpcDetectorPart::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::DmtpcDetectorPart*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *DmtpcDetectorPart::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::DmtpcDetectorPart*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void DmtpcDetectorPart::Streamer(TBuffer &R__b)
{
   // Stream an object of class DmtpcDetectorPart.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      TObject::Streamer(R__b);
      _localCoord.Streamer(R__b);
      R__b.ReadStaticArray((float*)_param);
      _comment.Streamer(R__b);
      _material.Streamer(R__b);
      void *ptr__shape = (void*)&_shape;
      R__b >> *reinterpret_cast<Int_t*>(ptr__shape);
      R__b >> _moduleID;
      R__b >> _partID;
      _serial.Streamer(R__b);
      R__b.CheckByteCount(R__s, R__c, DmtpcDetectorPart::IsA());
   } else {
      R__c = R__b.WriteVersion(DmtpcDetectorPart::IsA(), kTRUE);
      TObject::Streamer(R__b);
      _localCoord.Streamer(R__b);
      R__b.WriteArray(_param, 10);
      _comment.Streamer(R__b);
      _material.Streamer(R__b);
      R__b << (Int_t)_shape;
      R__b << _moduleID;
      R__b << _partID;
      _serial.Streamer(R__b);
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void DmtpcDetectorPart::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class DmtpcDetectorPart.
      TClass *R__cl = ::DmtpcDetectorPart::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "_localCoord", &_localCoord);
      R__insp.InspectMember(_localCoord, "_localCoord.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "_param[10]", _param);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "_comment", &_comment);
      R__insp.InspectMember(_comment, "_comment.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "_material", &_material);
      R__insp.InspectMember(_material, "_material.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "_shape", &_shape);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "_moduleID", &_moduleID);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "_partID", &_partID);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "_serial", &_serial);
      R__insp.InspectMember(_serial, "_serial.");
      TObject::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_DmtpcDetectorPart(void *p) {
      return  p ? new(p) ::DmtpcDetectorPart : new ::DmtpcDetectorPart;
   }
   static void *newArray_DmtpcDetectorPart(Long_t nElements, void *p) {
      return p ? new(p) ::DmtpcDetectorPart[nElements] : new ::DmtpcDetectorPart[nElements];
   }
   // Wrapper around operator delete
   static void delete_DmtpcDetectorPart(void *p) {
      delete ((::DmtpcDetectorPart*)p);
   }
   static void deleteArray_DmtpcDetectorPart(void *p) {
      delete [] ((::DmtpcDetectorPart*)p);
   }
   static void destruct_DmtpcDetectorPart(void *p) {
      typedef ::DmtpcDetectorPart current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_DmtpcDetectorPart(TBuffer &buf, void *obj) {
      ((::DmtpcDetectorPart*)obj)->::DmtpcDetectorPart::Streamer(buf);
   }
} // end of namespace ROOT for class ::DmtpcDetectorPart

/********************************************************
* DmtpcDetectorPartCint.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableDmtpcDetectorPartCint();

extern "C" void G__set_cpp_environmentDmtpcDetectorPartCint() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("DmtpcDetectorPart.hh");
  G__cpp_reset_tagtableDmtpcDetectorPartCint();
}
#include <new>
extern "C" int G__cpp_dllrevDmtpcDetectorPartCint() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* DmtpcDetectorPart */
static int G__DmtpcDetectorPartCint_249_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   DmtpcDetectorPart* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new DmtpcDetectorPart[n];
     } else {
       p = new((void*) gvp) DmtpcDetectorPart[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new DmtpcDetectorPart;
     } else {
       p = new((void*) gvp) DmtpcDetectorPart;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__DmtpcDetectorPartCintLN_DmtpcDetectorPart));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcDetectorPartCint_249_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   DmtpcDetectorPart* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 1
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new DmtpcDetectorPart((DmtpcDetectorPart::DmtpcPartShape) G__int(libp->para[0]));
   } else {
     p = new((void*) gvp) DmtpcDetectorPart((DmtpcDetectorPart::DmtpcPartShape) G__int(libp->para[0]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__DmtpcDetectorPartCintLN_DmtpcDetectorPart));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcDetectorPartCint_249_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   DmtpcDetectorPart* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 1
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new DmtpcDetectorPart(*(DmtpcDetectorPart*) libp->para[0].ref);
   } else {
     p = new((void*) gvp) DmtpcDetectorPart(*(DmtpcDetectorPart*) libp->para[0].ref);
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__DmtpcDetectorPartCintLN_DmtpcDetectorPart));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcDetectorPartCint_249_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((DmtpcDetectorPart*) G__getstructoffset())->setParameter((int) G__int(libp->para[0]), (float) G__double(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcDetectorPartCint_249_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((DmtpcDetectorPart*) G__getstructoffset())->getParameter((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcDetectorPartCint_249_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((DmtpcDetectorPart*) G__getstructoffset())->setLocalCoordinate(*((DmtpcLocation*) G__int(libp->para[0])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcDetectorPartCint_249_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         DmtpcLocation* pobj;
         DmtpcLocation xobj = ((DmtpcDetectorPart*) G__getstructoffset())->getLocalCoordinate();
         pobj = new DmtpcLocation(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcDetectorPartCint_249_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((DmtpcDetectorPart*) G__getstructoffset())->setComment(*((TString*) G__int(libp->para[0])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcDetectorPartCint_249_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         TString* pobj;
         TString xobj = ((DmtpcDetectorPart*) G__getstructoffset())->getComment();
         pobj = new TString(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcDetectorPartCint_249_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((DmtpcDetectorPart*) G__getstructoffset())->setMaterial(*((TString*) G__int(libp->para[0])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcDetectorPartCint_249_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         TString* pobj;
         TString xobj = ((DmtpcDetectorPart*) G__getstructoffset())->getMaterial();
         pobj = new TString(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcDetectorPartCint_249_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((DmtpcDetectorPart*) G__getstructoffset())->setShape((DmtpcDetectorPart::DmtpcPartShape) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcDetectorPartCint_249_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((DmtpcDetectorPart*) G__getstructoffset())->getShape());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcDetectorPartCint_249_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((DmtpcDetectorPart*) G__getstructoffset())->getModuleID());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcDetectorPartCint_249_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((DmtpcDetectorPart*) G__getstructoffset())->setModuleID((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcDetectorPartCint_249_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((DmtpcDetectorPart*) G__getstructoffset())->getPartID());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcDetectorPartCint_249_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((DmtpcDetectorPart*) G__getstructoffset())->setPartID((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcDetectorPartCint_249_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         TString* pobj;
         TString xobj = ((DmtpcDetectorPart*) G__getstructoffset())->getSN();
         pobj = new TString(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcDetectorPartCint_249_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((DmtpcDetectorPart*) G__getstructoffset())->setSN(*((TString*) G__int(libp->para[0])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcDetectorPartCint_249_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) DmtpcDetectorPart::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcDetectorPartCint_249_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) DmtpcDetectorPart::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcDetectorPartCint_249_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) DmtpcDetectorPart::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcDetectorPartCint_249_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      DmtpcDetectorPart::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcDetectorPartCint_249_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((DmtpcDetectorPart*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcDetectorPartCint_249_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) DmtpcDetectorPart::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcDetectorPartCint_249_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) DmtpcDetectorPart::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcDetectorPartCint_249_0_31(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) DmtpcDetectorPart::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DmtpcDetectorPartCint_249_0_32(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) DmtpcDetectorPart::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef DmtpcDetectorPart G__TDmtpcDetectorPart;
static int G__DmtpcDetectorPartCint_249_0_33(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (DmtpcDetectorPart*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((DmtpcDetectorPart*) (soff+(sizeof(DmtpcDetectorPart)*i)))->~G__TDmtpcDetectorPart();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (DmtpcDetectorPart*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((DmtpcDetectorPart*) (soff))->~G__TDmtpcDetectorPart();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__DmtpcDetectorPartCint_249_0_34(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   DmtpcDetectorPart* dest = (DmtpcDetectorPart*) G__getstructoffset();
   *dest = *(DmtpcDetectorPart*) libp->para[0].ref;
   const DmtpcDetectorPart& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* DmtpcDetectorPart */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncDmtpcDetectorPartCint {
 public:
  G__Sizep2memfuncDmtpcDetectorPartCint(): p(&G__Sizep2memfuncDmtpcDetectorPartCint::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncDmtpcDetectorPartCint::*p)();
};

size_t G__get_sizep2memfuncDmtpcDetectorPartCint()
{
  G__Sizep2memfuncDmtpcDetectorPartCint a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceDmtpcDetectorPartCint() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__DmtpcDetectorPartCintLN_DmtpcDetectorPart))) {
     DmtpcDetectorPart *G__Lderived;
     G__Lderived=(DmtpcDetectorPart*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__DmtpcDetectorPartCintLN_DmtpcDetectorPart),G__get_linked_tagnum(&G__DmtpcDetectorPartCintLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableDmtpcDetectorPartCint() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__DmtpcDetectorPartCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__DmtpcDetectorPartCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DmtpcDetectorPartCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__DmtpcDetectorPartCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DmtpcDetectorPartCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__DmtpcDetectorPartCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__DmtpcDetectorPartCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DmtpcDetectorPartCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__DmtpcDetectorPartCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DmtpcDetectorPartCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__DmtpcDetectorPartCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__DmtpcDetectorPartCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__DmtpcDetectorPartCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__DmtpcDetectorPartCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__DmtpcDetectorPartCintLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__DmtpcDetectorPartCintLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__DmtpcDetectorPartCintLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__DmtpcDetectorPartCintLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixT<Float_t>",117,G__get_linked_tagnum(&G__DmtpcDetectorPartCintLN_TMatrixTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow_const<Float_t>",117,G__get_linked_tagnum(&G__DmtpcDetectorPartCintLN_TMatrixTRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn_const<Float_t>",117,G__get_linked_tagnum(&G__DmtpcDetectorPartCintLN_TMatrixTColumn_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag_const<Float_t>",117,G__get_linked_tagnum(&G__DmtpcDetectorPartCintLN_TMatrixTDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat_const<Float_t>",117,G__get_linked_tagnum(&G__DmtpcDetectorPartCintLN_TMatrixTFlat_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub_const<Float_t>",117,G__get_linked_tagnum(&G__DmtpcDetectorPartCintLN_TMatrixTSub_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow_const<Float_t>",117,G__get_linked_tagnum(&G__DmtpcDetectorPartCintLN_TMatrixTSparseRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag_const<Float_t>",117,G__get_linked_tagnum(&G__DmtpcDetectorPartCintLN_TMatrixTSparseDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow<Float_t>",117,G__get_linked_tagnum(&G__DmtpcDetectorPartCintLN_TMatrixTRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn<Float_t>",117,G__get_linked_tagnum(&G__DmtpcDetectorPartCintLN_TMatrixTColumnlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag<Float_t>",117,G__get_linked_tagnum(&G__DmtpcDetectorPartCintLN_TMatrixTDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat<Float_t>",117,G__get_linked_tagnum(&G__DmtpcDetectorPartCintLN_TMatrixTFlatlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub<Float_t>",117,G__get_linked_tagnum(&G__DmtpcDetectorPartCintLN_TMatrixTSublEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow<Float_t>",117,G__get_linked_tagnum(&G__DmtpcDetectorPartCintLN_TMatrixTSparseRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag<Float_t>",117,G__get_linked_tagnum(&G__DmtpcDetectorPartCintLN_TMatrixTSparseDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementActionT<Float_t>",117,G__get_linked_tagnum(&G__DmtpcDetectorPartCintLN_TElementActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementPosActionT<Float_t>",117,G__get_linked_tagnum(&G__DmtpcDetectorPartCintLN_TElementPosActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* DmtpcDetectorPart */
static void G__setup_memvarDmtpcDetectorPart(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__DmtpcDetectorPartCintLN_DmtpcDetectorPart));
   { DmtpcDetectorPart *p; p=(DmtpcDetectorPart*)0x1000; if (p) { }
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__DmtpcDetectorPartCintLN_DmtpcDetectorPartcLcLDmtpcPartShape),-1,-2,1,G__FastAllocString(2048).Format("kCylinder=%lldLL",(long long)DmtpcDetectorPart::kCylinder).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__DmtpcDetectorPartCintLN_DmtpcDetectorPartcLcLDmtpcPartShape),-1,-2,1,G__FastAllocString(2048).Format("kCuboid=%lldLL",(long long)DmtpcDetectorPart::kCuboid).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__DmtpcDetectorPartCintLN_DmtpcDetectorPartcLcLDmtpcPartShape),-1,-2,1,G__FastAllocString(2048).Format("kSphere=%lldLL",(long long)DmtpcDetectorPart::kSphere).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__DmtpcDetectorPartCintLN_DmtpcDetectorPartcLcLDmtpcPartShape),-1,-2,1,G__FastAllocString(2048).Format("kOther=%lldLL",(long long)DmtpcDetectorPart::kOther).data(),0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__DmtpcDetectorPartCintLN_DmtpcLocation),-1,-1,4,"_localCoord=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"_param[10]=",0,"parameters to describe the part");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__DmtpcDetectorPartCintLN_TString),-1,-1,4,"_comment=",0,"Comment about detector part, shape, purpose, etc.");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__DmtpcDetectorPartCintLN_TString),-1,-1,4,"_material=",0,"Description of material; e.g. SS104, Cu101, etc");
   G__memvar_setup((void*)0,105,0,0,G__get_linked_tagnum(&G__DmtpcDetectorPartCintLN_DmtpcDetectorPartcLcLDmtpcPartShape),-1,-1,4,"_shape=",0,"geometrical shape of object");
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"_moduleID=",0,"module identification for multi-module run");
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"_partID=",0,"part number inside a module");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__DmtpcDetectorPartCintLN_TString),-1,-1,4,"_serial=",0,"alphanumeric serial tag by manufacturer");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DmtpcDetectorPartCintLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarDmtpcDetectorPartCint() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncDmtpcDetectorPart(void) {
   /* DmtpcDetectorPart */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__DmtpcDetectorPartCintLN_DmtpcDetectorPart));
   G__memfunc_setup("DmtpcDetectorPart",1737,G__DmtpcDetectorPartCint_249_0_1, 105, G__get_linked_tagnum(&G__DmtpcDetectorPartCintLN_DmtpcDetectorPart), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DmtpcDetectorPart",1737,G__DmtpcDetectorPartCint_249_0_2, 105, G__get_linked_tagnum(&G__DmtpcDetectorPartCintLN_DmtpcDetectorPart), -1, 0, 1, 1, 1, 0, "i 'DmtpcDetectorPart::DmtpcPartShape' - 0 - geo", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DmtpcDetectorPart",1737,G__DmtpcDetectorPartCint_249_0_3, 105, G__get_linked_tagnum(&G__DmtpcDetectorPartCintLN_DmtpcDetectorPart), -1, 0, 1, 1, 1, 0, "u 'DmtpcDetectorPart' - 11 - other", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetName",673,(G__InterfaceMethod) NULL,67, -1, -1, 0, 0, 1, 1, 9, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("setParameter",1261,G__DmtpcDetectorPartCint_249_0_5, 121, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - i f - - 0 - val", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getParameter",1249,G__DmtpcDetectorPartCint_249_0_6, 102, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setLocalCoordinate",1855,G__DmtpcDetectorPartCint_249_0_7, 121, -1, -1, 0, 1, 1, 1, 0, "u 'DmtpcLocation' - 0 - loc", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getLocalCoordinate",1843,G__DmtpcDetectorPartCint_249_0_8, 117, G__get_linked_tagnum(&G__DmtpcDetectorPartCintLN_DmtpcLocation), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setComment",1055,G__DmtpcDetectorPartCint_249_0_9, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TString' - 0 - com", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getComment",1043,G__DmtpcDetectorPartCint_249_0_10, 117, G__get_linked_tagnum(&G__DmtpcDetectorPartCintLN_TString), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setMaterial",1147,G__DmtpcDetectorPartCint_249_0_11, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TString' - 0 - mat", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getMaterial",1135,G__DmtpcDetectorPartCint_249_0_12, 117, G__get_linked_tagnum(&G__DmtpcDetectorPartCintLN_TString), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setShape",829,G__DmtpcDetectorPartCint_249_0_13, 121, -1, -1, 0, 1, 1, 1, 0, "i 'DmtpcDetectorPart::DmtpcPartShape' - 0 - sh", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getShape",817,G__DmtpcDetectorPartCint_249_0_14, 105, G__get_linked_tagnum(&G__DmtpcDetectorPartCintLN_DmtpcDetectorPartcLcLDmtpcPartShape), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getModuleID",1075,G__DmtpcDetectorPartCint_249_0_15, 105, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setModuleID",1087,G__DmtpcDetectorPartCint_249_0_16, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - id", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getPartID",868,G__DmtpcDetectorPartCint_249_0_17, 105, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setPartID",880,G__DmtpcDetectorPartCint_249_0_18, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - id", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getSN",481,G__DmtpcDetectorPartCint_249_0_19, 117, G__get_linked_tagnum(&G__DmtpcDetectorPartCintLN_TString), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setSN",493,G__DmtpcDetectorPartCint_249_0_20, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TString' - 0 - ser", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__DmtpcDetectorPartCint_249_0_21, 85, G__get_linked_tagnum(&G__DmtpcDetectorPartCintLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&DmtpcDetectorPart::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__DmtpcDetectorPartCint_249_0_22, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&DmtpcDetectorPart::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__DmtpcDetectorPartCint_249_0_23, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&DmtpcDetectorPart::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__DmtpcDetectorPartCint_249_0_24, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&DmtpcDetectorPart::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__DmtpcDetectorPartCintLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - insp", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__DmtpcDetectorPartCint_249_0_28, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__DmtpcDetectorPartCint_249_0_29, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&DmtpcDetectorPart::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__DmtpcDetectorPartCint_249_0_30, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&DmtpcDetectorPart::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__DmtpcDetectorPartCint_249_0_31, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&DmtpcDetectorPart::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__DmtpcDetectorPartCint_249_0_32, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&DmtpcDetectorPart::DeclFileLine) ), 0);
   // automatic destructor
   G__memfunc_setup("~DmtpcDetectorPart", 1863, G__DmtpcDetectorPartCint_249_0_33, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__DmtpcDetectorPartCint_249_0_34, (int) ('u'), G__get_linked_tagnum(&G__DmtpcDetectorPartCintLN_DmtpcDetectorPart), -1, 1, 1, 1, 1, 0, "u 'DmtpcDetectorPart' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncDmtpcDetectorPartCint() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalDmtpcDetectorPartCint() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcDmtpcDetectorPartCint() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__DmtpcDetectorPartCintLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__DmtpcDetectorPartCintLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__DmtpcDetectorPartCintLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__DmtpcDetectorPartCintLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__DmtpcDetectorPartCintLN_TString = { "TString" , 99 , -1 };
G__linked_taginfo G__DmtpcDetectorPartCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__DmtpcDetectorPartCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__DmtpcDetectorPartCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__DmtpcDetectorPartCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__DmtpcDetectorPartCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__DmtpcDetectorPartCintLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__DmtpcDetectorPartCintLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__DmtpcDetectorPartCintLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__DmtpcDetectorPartCintLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__DmtpcDetectorPartCintLN_TElementActionTlEfloatgR = { "TElementActionT<float>" , 99 , -1 };
G__linked_taginfo G__DmtpcDetectorPartCintLN_TElementPosActionTlEfloatgR = { "TElementPosActionT<float>" , 99 , -1 };
G__linked_taginfo G__DmtpcDetectorPartCintLN_TMatrixTlEfloatgR = { "TMatrixT<float>" , 99 , -1 };
G__linked_taginfo G__DmtpcDetectorPartCintLN_TMatrixTRow_constlEfloatgR = { "TMatrixTRow_const<float>" , 99 , -1 };
G__linked_taginfo G__DmtpcDetectorPartCintLN_TMatrixTRowlEfloatgR = { "TMatrixTRow<float>" , 99 , -1 };
G__linked_taginfo G__DmtpcDetectorPartCintLN_TMatrixTDiag_constlEfloatgR = { "TMatrixTDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__DmtpcDetectorPartCintLN_TMatrixTColumn_constlEfloatgR = { "TMatrixTColumn_const<float>" , 99 , -1 };
G__linked_taginfo G__DmtpcDetectorPartCintLN_TMatrixTFlat_constlEfloatgR = { "TMatrixTFlat_const<float>" , 99 , -1 };
G__linked_taginfo G__DmtpcDetectorPartCintLN_TMatrixTSub_constlEfloatgR = { "TMatrixTSub_const<float>" , 99 , -1 };
G__linked_taginfo G__DmtpcDetectorPartCintLN_TMatrixTSparseRow_constlEfloatgR = { "TMatrixTSparseRow_const<float>" , 99 , -1 };
G__linked_taginfo G__DmtpcDetectorPartCintLN_TMatrixTSparseDiag_constlEfloatgR = { "TMatrixTSparseDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__DmtpcDetectorPartCintLN_TMatrixTColumnlEfloatgR = { "TMatrixTColumn<float>" , 99 , -1 };
G__linked_taginfo G__DmtpcDetectorPartCintLN_TMatrixTDiaglEfloatgR = { "TMatrixTDiag<float>" , 99 , -1 };
G__linked_taginfo G__DmtpcDetectorPartCintLN_TMatrixTFlatlEfloatgR = { "TMatrixTFlat<float>" , 99 , -1 };
G__linked_taginfo G__DmtpcDetectorPartCintLN_TMatrixTSublEfloatgR = { "TMatrixTSub<float>" , 99 , -1 };
G__linked_taginfo G__DmtpcDetectorPartCintLN_TMatrixTSparseRowlEfloatgR = { "TMatrixTSparseRow<float>" , 99 , -1 };
G__linked_taginfo G__DmtpcDetectorPartCintLN_TMatrixTSparseDiaglEfloatgR = { "TMatrixTSparseDiag<float>" , 99 , -1 };
G__linked_taginfo G__DmtpcDetectorPartCintLN_DmtpcLocation = { "DmtpcLocation" , 99 , -1 };
G__linked_taginfo G__DmtpcDetectorPartCintLN_DmtpcDetectorPart = { "DmtpcDetectorPart" , 99 , -1 };
G__linked_taginfo G__DmtpcDetectorPartCintLN_DmtpcDetectorPartcLcLDmtpcPartShape = { "DmtpcDetectorPart::DmtpcPartShape" , 101 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableDmtpcDetectorPartCint() {
  G__DmtpcDetectorPartCintLN_TClass.tagnum = -1 ;
  G__DmtpcDetectorPartCintLN_TBuffer.tagnum = -1 ;
  G__DmtpcDetectorPartCintLN_TMemberInspector.tagnum = -1 ;
  G__DmtpcDetectorPartCintLN_TObject.tagnum = -1 ;
  G__DmtpcDetectorPartCintLN_TString.tagnum = -1 ;
  G__DmtpcDetectorPartCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__DmtpcDetectorPartCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__DmtpcDetectorPartCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__DmtpcDetectorPartCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__DmtpcDetectorPartCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__DmtpcDetectorPartCintLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__DmtpcDetectorPartCintLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__DmtpcDetectorPartCintLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__DmtpcDetectorPartCintLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__DmtpcDetectorPartCintLN_TElementActionTlEfloatgR.tagnum = -1 ;
  G__DmtpcDetectorPartCintLN_TElementPosActionTlEfloatgR.tagnum = -1 ;
  G__DmtpcDetectorPartCintLN_TMatrixTlEfloatgR.tagnum = -1 ;
  G__DmtpcDetectorPartCintLN_TMatrixTRow_constlEfloatgR.tagnum = -1 ;
  G__DmtpcDetectorPartCintLN_TMatrixTRowlEfloatgR.tagnum = -1 ;
  G__DmtpcDetectorPartCintLN_TMatrixTDiag_constlEfloatgR.tagnum = -1 ;
  G__DmtpcDetectorPartCintLN_TMatrixTColumn_constlEfloatgR.tagnum = -1 ;
  G__DmtpcDetectorPartCintLN_TMatrixTFlat_constlEfloatgR.tagnum = -1 ;
  G__DmtpcDetectorPartCintLN_TMatrixTSub_constlEfloatgR.tagnum = -1 ;
  G__DmtpcDetectorPartCintLN_TMatrixTSparseRow_constlEfloatgR.tagnum = -1 ;
  G__DmtpcDetectorPartCintLN_TMatrixTSparseDiag_constlEfloatgR.tagnum = -1 ;
  G__DmtpcDetectorPartCintLN_TMatrixTColumnlEfloatgR.tagnum = -1 ;
  G__DmtpcDetectorPartCintLN_TMatrixTDiaglEfloatgR.tagnum = -1 ;
  G__DmtpcDetectorPartCintLN_TMatrixTFlatlEfloatgR.tagnum = -1 ;
  G__DmtpcDetectorPartCintLN_TMatrixTSublEfloatgR.tagnum = -1 ;
  G__DmtpcDetectorPartCintLN_TMatrixTSparseRowlEfloatgR.tagnum = -1 ;
  G__DmtpcDetectorPartCintLN_TMatrixTSparseDiaglEfloatgR.tagnum = -1 ;
  G__DmtpcDetectorPartCintLN_DmtpcLocation.tagnum = -1 ;
  G__DmtpcDetectorPartCintLN_DmtpcDetectorPart.tagnum = -1 ;
  G__DmtpcDetectorPartCintLN_DmtpcDetectorPartcLcLDmtpcPartShape.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableDmtpcDetectorPartCint() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__DmtpcDetectorPartCintLN_TClass);
   G__get_linked_tagnum_fwd(&G__DmtpcDetectorPartCintLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__DmtpcDetectorPartCintLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__DmtpcDetectorPartCintLN_TObject);
   G__get_linked_tagnum_fwd(&G__DmtpcDetectorPartCintLN_TString);
   G__get_linked_tagnum_fwd(&G__DmtpcDetectorPartCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__DmtpcDetectorPartCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__DmtpcDetectorPartCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__DmtpcDetectorPartCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__DmtpcDetectorPartCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__DmtpcDetectorPartCintLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__DmtpcDetectorPartCintLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__DmtpcDetectorPartCintLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__DmtpcDetectorPartCintLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__DmtpcDetectorPartCintLN_TElementActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__DmtpcDetectorPartCintLN_TElementPosActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__DmtpcDetectorPartCintLN_TMatrixTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__DmtpcDetectorPartCintLN_TMatrixTRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__DmtpcDetectorPartCintLN_TMatrixTRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__DmtpcDetectorPartCintLN_TMatrixTDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__DmtpcDetectorPartCintLN_TMatrixTColumn_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__DmtpcDetectorPartCintLN_TMatrixTFlat_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__DmtpcDetectorPartCintLN_TMatrixTSub_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__DmtpcDetectorPartCintLN_TMatrixTSparseRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__DmtpcDetectorPartCintLN_TMatrixTSparseDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__DmtpcDetectorPartCintLN_TMatrixTColumnlEfloatgR);
   G__get_linked_tagnum_fwd(&G__DmtpcDetectorPartCintLN_TMatrixTDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__DmtpcDetectorPartCintLN_TMatrixTFlatlEfloatgR);
   G__get_linked_tagnum_fwd(&G__DmtpcDetectorPartCintLN_TMatrixTSublEfloatgR);
   G__get_linked_tagnum_fwd(&G__DmtpcDetectorPartCintLN_TMatrixTSparseRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__DmtpcDetectorPartCintLN_TMatrixTSparseDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__DmtpcDetectorPartCintLN_DmtpcLocation);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__DmtpcDetectorPartCintLN_DmtpcDetectorPart),sizeof(DmtpcDetectorPart),-1,63232,(char*)NULL,G__setup_memvarDmtpcDetectorPart,G__setup_memfuncDmtpcDetectorPart);
   G__get_linked_tagnum_fwd(&G__DmtpcDetectorPartCintLN_DmtpcDetectorPartcLcLDmtpcPartShape);
}
extern "C" void G__cpp_setupDmtpcDetectorPartCint(void) {
  G__check_setup_version(30051515,"G__cpp_setupDmtpcDetectorPartCint()");
  G__set_cpp_environmentDmtpcDetectorPartCint();
  G__cpp_setup_tagtableDmtpcDetectorPartCint();

  G__cpp_setup_inheritanceDmtpcDetectorPartCint();

  G__cpp_setup_typetableDmtpcDetectorPartCint();

  G__cpp_setup_memvarDmtpcDetectorPartCint();

  G__cpp_setup_memfuncDmtpcDetectorPartCint();
  G__cpp_setup_globalDmtpcDetectorPartCint();
  G__cpp_setup_funcDmtpcDetectorPartCint();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncDmtpcDetectorPartCint();
  return;
}
class G__cpp_setup_initDmtpcDetectorPartCint {
  public:
    G__cpp_setup_initDmtpcDetectorPartCint() { G__add_setup_func("DmtpcDetectorPartCint",(G__incsetup)(&G__cpp_setupDmtpcDetectorPartCint)); G__call_setup_funcs(); }
   ~G__cpp_setup_initDmtpcDetectorPartCint() { G__remove_setup_func("DmtpcDetectorPartCint"); }
};
G__cpp_setup_initDmtpcDetectorPartCint G__cpp_setup_initializerDmtpcDetectorPartCint;

