/********************************************************************
* MaxCamTriggerGroupCint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error MaxCamTriggerGroupCint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableMaxCamTriggerGroupCint();
extern void G__cpp_setup_inheritanceMaxCamTriggerGroupCint();
extern void G__cpp_setup_typetableMaxCamTriggerGroupCint();
extern void G__cpp_setup_memvarMaxCamTriggerGroupCint();
extern void G__cpp_setup_globalMaxCamTriggerGroupCint();
extern void G__cpp_setup_memfuncMaxCamTriggerGroupCint();
extern void G__cpp_setup_funcMaxCamTriggerGroupCint();
extern void G__set_cpp_environmentMaxCamTriggerGroupCint();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "MaxCamTriggerGroup.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__MaxCamTriggerGroupCintLN_TClass;
extern G__linked_taginfo G__MaxCamTriggerGroupCintLN_TBuffer;
extern G__linked_taginfo G__MaxCamTriggerGroupCintLN_TMemberInspector;
extern G__linked_taginfo G__MaxCamTriggerGroupCintLN_TObject;
extern G__linked_taginfo G__MaxCamTriggerGroupCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__MaxCamTriggerGroupCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__MaxCamTriggerGroupCintLN_TObjArray;
extern G__linked_taginfo G__MaxCamTriggerGroupCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__MaxCamTriggerGroupCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__MaxCamTriggerGroupCintLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__MaxCamTriggerGroupCintLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__MaxCamTriggerGroupCintLN_listlEMaxCamPulsecOallocatorlEMaxCamPulsegRsPgR;
extern G__linked_taginfo G__MaxCamTriggerGroupCintLN_MaxCamWaveform;
extern G__linked_taginfo G__MaxCamTriggerGroupCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__MaxCamTriggerGroupCintLN_MaxCamTriggerGroup;

/* STUB derived class for protected member access */
