/********************************************************************
* MaxCamWaveformToolsCint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error MaxCamWaveformToolsCint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableMaxCamWaveformToolsCint();
extern void G__cpp_setup_inheritanceMaxCamWaveformToolsCint();
extern void G__cpp_setup_typetableMaxCamWaveformToolsCint();
extern void G__cpp_setup_memvarMaxCamWaveformToolsCint();
extern void G__cpp_setup_globalMaxCamWaveformToolsCint();
extern void G__cpp_setup_memfuncMaxCamWaveformToolsCint();
extern void G__cpp_setup_funcMaxCamWaveformToolsCint();
extern void G__set_cpp_environmentMaxCamWaveformToolsCint();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "MaxCamWaveformTools.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__MaxCamWaveformToolsCintLN_TClass;
extern G__linked_taginfo G__MaxCamWaveformToolsCintLN_TBuffer;
extern G__linked_taginfo G__MaxCamWaveformToolsCintLN_TMemberInspector;
extern G__linked_taginfo G__MaxCamWaveformToolsCintLN_TObject;
extern G__linked_taginfo G__MaxCamWaveformToolsCintLN_TString;
extern G__linked_taginfo G__MaxCamWaveformToolsCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__MaxCamWaveformToolsCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__MaxCamWaveformToolsCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__MaxCamWaveformToolsCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__MaxCamWaveformToolsCintLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__MaxCamWaveformToolsCintLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__MaxCamWaveformToolsCintLN_TF1;
extern G__linked_taginfo G__MaxCamWaveformToolsCintLN_TH1;
extern G__linked_taginfo G__MaxCamWaveformToolsCintLN_TH1F;
extern G__linked_taginfo G__MaxCamWaveformToolsCintLN_TGraph;
extern G__linked_taginfo G__MaxCamWaveformToolsCintLN_MaxCamPulse;
extern G__linked_taginfo G__MaxCamWaveformToolsCintLN_MaxCamWaveformTools;
extern G__linked_taginfo G__MaxCamWaveformToolsCintLN_listlEMaxCamPulsecOallocatorlEMaxCamPulsegRsPgR;

/* STUB derived class for protected member access */
