/********************************************************************
* RobinHoodTriangleMakerCint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error RobinHoodTriangleMakerCint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableRobinHoodTriangleMakerCint();
extern void G__cpp_setup_inheritanceRobinHoodTriangleMakerCint();
extern void G__cpp_setup_typetableRobinHoodTriangleMakerCint();
extern void G__cpp_setup_memvarRobinHoodTriangleMakerCint();
extern void G__cpp_setup_globalRobinHoodTriangleMakerCint();
extern void G__cpp_setup_memfuncRobinHoodTriangleMakerCint();
extern void G__cpp_setup_funcRobinHoodTriangleMakerCint();
extern void G__set_cpp_environmentRobinHoodTriangleMakerCint();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "RobinHoodTriangleMaker.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__RobinHoodTriangleMakerCintLN_TClass;
extern G__linked_taginfo G__RobinHoodTriangleMakerCintLN_TBuffer;
extern G__linked_taginfo G__RobinHoodTriangleMakerCintLN_TMemberInspector;
extern G__linked_taginfo G__RobinHoodTriangleMakerCintLN_TObject;
extern G__linked_taginfo G__RobinHoodTriangleMakerCintLN_TString;
extern G__linked_taginfo G__RobinHoodTriangleMakerCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__RobinHoodTriangleMakerCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__RobinHoodTriangleMakerCintLN_TList;
extern G__linked_taginfo G__RobinHoodTriangleMakerCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__RobinHoodTriangleMakerCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__RobinHoodTriangleMakerCintLN_TVector3;
extern G__linked_taginfo G__RobinHoodTriangleMakerCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__RobinHoodTriangleMakerCintLN_RobinHoodTriangleMaker;

/* STUB derived class for protected member access */
