/********************************************************************
* ScopeDataInfoCint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ScopeDataInfoCint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableScopeDataInfoCint();
extern void G__cpp_setup_inheritanceScopeDataInfoCint();
extern void G__cpp_setup_typetableScopeDataInfoCint();
extern void G__cpp_setup_memvarScopeDataInfoCint();
extern void G__cpp_setup_globalScopeDataInfoCint();
extern void G__cpp_setup_memfuncScopeDataInfoCint();
extern void G__cpp_setup_funcScopeDataInfoCint();
extern void G__set_cpp_environmentScopeDataInfoCint();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "ScopeDataInfo.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__ScopeDataInfoCintLN_TClass;
extern G__linked_taginfo G__ScopeDataInfoCintLN_TBuffer;
extern G__linked_taginfo G__ScopeDataInfoCintLN_TMemberInspector;
extern G__linked_taginfo G__ScopeDataInfoCintLN_TObject;
extern G__linked_taginfo G__ScopeDataInfoCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__ScopeDataInfoCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ScopeDataInfoCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__ScopeDataInfoCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ScopeDataInfoCintLN_ScopeInputCoupling;
extern G__linked_taginfo G__ScopeDataInfoCintLN_ScopeTriggerSlope;
extern G__linked_taginfo G__ScopeDataInfoCintLN_ScopeDataInfo;

/* STUB derived class for protected member access */
