#! /usr/bin/env python
import os

def execSQLite3(cmd="",db="mccfg.db"):
    os.system("sqlite3 -line "+db+" \""+cmd+"\"")

def addColumn(name,type="text",db="mccfg.db",table="mccfg"):
    execSQLite3("alter table "+table+" add column \`"+name+"\` "+type,db)

def main():

    execSQLite3("drop table mccfg")

    execSQLite3("CREATE TABLE \`mccfg\` (\`mccfgdb_id\` integer primary key,\`mccfgdb_timestamp\` timestamp NOT NULL default CURRENT_TIMESTAMP,\`mccfgdb_userid\` text NOT NULL)")

    # run parameters
    addColumn("RunProperties.NumberOfEvents","text default NULL")
    addColumn("RunProperties.FileTag","text default NULL")
    addColumn("RunProperties.DataFile","text default NULL")
    addColumn("RunProperties.TextFile","text default NULL")
    addColumn("RunProperties.DataPath","text default NULL")
    addColumn("RunProperties.TextPath","text default NULL")
    addColumn("RunProperties.EventType","text default NULL")
    addColumn("RunProperties.ProjectileParticle","text default NULL")
    addColumn("RunProperties.ProjectileMass","text default NULL")
    addColumn("RunProperties.RecoilParticle","text default NULL")
    addColumn("RunProperties.RecoilMass","text default NULL")
    addColumn("RunProperties.SRIMfile","text default NULL")
    addColumn("RunProperties.Location","text default NULL")
    addColumn("RunProperties.EnergyOption","text default NULL")
    addColumn("RunProperties.DecayChain","text default NULL")
    addColumn("RunProperties.MinEnergy","text default NULL")
    addColumn("RunProperties.MaxEnergy","text default NULL")
    addColumn("RunProperties.FixEnergy","text default NULL")
    addColumn("RunProperties.EnergySpread","text default NULL")
    addColumn("RunProperties.PositionOption","text default NULL")
    addColumn("RunProperties.MinPositionLimits","text default NULL")
    addColumn("RunProperties.MaxPositionLimits","text default NULL")
    addColumn("RunProperties.RingPositionValues","text default NULL")
    addColumn("RunProperties.FixPosition","text default NULL")
    addColumn("RunProperties.TimeOption","text default NULL")
    addColumn("RunProperties.MinTime","text default NULL")
    addColumn("RunProperties.MaxTime","text default NULL")
    addColumn("RunProperties.FixTime","text default NULL")
    addColumn("RunProperties.TimeStep","text default NULL")
    addColumn("RunProperties.DirectionOption","text default NULL")
    addColumn("RunProperties.SourcePosition","text default NULL")
    addColumn("RunProperties.SourceDirection","text default NULL")
    addColumn("RunProperties.ThetaMax","text default NULL")
    addColumn("RunProperties.SpecialOption","text default NULL")
    addColumn("RunProperties.FissionSpectrumENDF","text default NULL")
    addColumn("RunProperties.TotalCS_ENDF","text default NULL")
    addColumn("RunProperties.ElastScatterDCS_ENDF","text default NULL")
    addColumn("RunProperties.TimeResolution","text default NULL")
    addColumn("RunProperties.WimpEnergyOption","text default NULL")
    addColumn("RunProperties.SaveTrueClusters","text default NULL")
    addColumn("RunProperties.MinimumMatchingDataRunNumber","text default NULL")
    addColumn("RunProperties.MaximumMatchingDataRunNumber","text default NULL")
    addColumn("RunProperties.Comment","text default NULL")

    # scope properties
    addColumn("ScopeProperties.BoardType","text default NULL")
    addColumn("ScopeProperties.SerialNumber","text default NULL")
    addColumn("ScopeProperties.ClockRate","text default NULL")
    addColumn("ScopeProperties.RecordPreSize","text default NULL")
    addColumn("ScopeProperties.RecordLength","text default NULL")
    addColumn("ScopeProperties.ChannelName","text default NULL")
    addColumn("ScopeProperties.ConnectedDevice","text default NULL")
    addColumn("ScopeProperties.VoltageMin","text default NULL")
    addColumn("ScopeProperties.VoltageMax","text default NULL")
    addColumn("ScopeProperties.ScopeNumber","text default NULL")

    # pmt properties
    addColumn("PMTProperties.PMTPosition","text default NULL")
    addColumn("PMTProperties.SerialNumber","text default NULL")
    addColumn("PMTProperties.PMTDiameter","text default NULL")
    addColumn("PMTProperties.PMTDistance","text default NULL")
    addColumn("PMTProperties.PMTNumber","text default NULL")

    # camera properties
    addColumn("CameraProperties.CameraPosition","text default NULL")
    addColumn("CameraProperties.SerialNumber","text default NULL")
    addColumn("CameraProperties.CameraBins","text default NULL")
    addColumn("CameraProperties.ImageWidths","text default NULL")
    addColumn("CameraProperties.PixelsPerBin","text default NULL")
    addColumn("CameraProperties.ReadNoise","text default NULL")
    addColumn("CameraProperties.Bias","text default NULL")
    addColumn("CameraProperties.Gain","text default NULL")
    addColumn("CameraProperties.GainMap","text default NULL")
    addColumn("CameraProperties.ActiveRegionUnits","text default NULL")
    addColumn("CameraProperties.ActiveRegion","text default NULL")
    addColumn("CameraProperties.NoiseFactor","text default NULL")
    addColumn("CameraProperties.DarkCurrent","text default NULL")
    addColumn("CameraProperties.EMGain","text default NULL")
    addColumn("CameraProperties.CameraNumber","text default NULL")

    # detector properties
    addColumn("DetectorProperties.SpacerDiameter","text default NULL")
    addColumn("DetectorProperties.SpacerSpacing","text default NULL")
    addColumn("DetectorProperties.Temperature","text default NULL")
    addColumn("DetectorProperties.SpacerAxis","text default NULL")
    addColumn("DetectorProperties.Height","text default NULL")
    addColumn("DetectorProperties.DriftLength","text default NULL")
    addColumn("DetectorProperties.Pressure","text default NULL")
    addColumn("DetectorProperties.DriftVoltage","text default NULL")
    addColumn("DetectorProperties.AnodeVoltage","text default NULL")
    addColumn("DetectorProperties.DiffusionConstantTerm","text default NULL")
    addColumn("DetectorProperties.DiffusionDzTerm","text default NULL")
    addColumn("DetectorProperties.ElectricScintillation","text default NULL")
    addColumn("DetectorProperties.NuclearScintillation","text default NULL")
    addColumn("DetectorProperties.Attenuation","text default NULL")
    addColumn("DetectorProperties.ElectronPerkeV","text default NULL")
    addColumn("DetectorProperties.DriftVelocity","text default NULL")
    addColumn("DetectorProperties.LongDiffusionConstTerm","text default NULL")
    addColumn("DetectorProperties.LongDiffusionDzTerm","text default NULL")
    addColumn("DetectorProperties.OrientationAngle","text default NULL")
    addColumn("DetectorProperties.TopOrBottomTPC","text default NULL")
    
if __name__ == '__main__':
    main()
